// Workbench DOM/UI layer, extracted verbatim from paper-rig-workbench.html.
// A script fragment concatenated after the pipeline + builders by
// `rig build-workbench`. Owns the mutable `state` the pure pipeline reads.
/* eslint-disable */
document.querySelector('.tag').textContent=`${C.schema} · schema ${C.schemaVersion} · generator ${C.generatorVersion}`;
const defaultModelTransform=id=>({move:[0,0,0],rot:[...(rigs[id].bindCorrection?.rotationXYZDegrees||[0,0,0])]});
let state={model:'horse',clip:'idle',t:0,playing:false,lastPaint:performance.now(),elev:90,az:0,height:1,width:1,bones:true,contacts:true,transformTarget:'model',selection:null,modelTransforms:Object.fromEntries(Object.keys(rigs).map(id=>[id,defaultModelTransform(id)])),jointTransforms:Object.fromEntries(Object.keys(rigs).map(id=>[id,{}]))};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function editorViewBox(rig,t,clip){const P=projected(worldJoints(rig,t,clip),'projected',rig),pts=Object.values(P),xs=pts.map(p=>p[0]),ys=pts.map(p=>p[1]),plateExtent=Math.max(...rig.plates.filter(p=>p.role!=='shadow').flatMap(p=>p.size||[0]))*rig.tokenScale,pad=Math.max(8,Math.min(14,plateExtent*.45)),minX=Math.min(...xs)-pad,maxX=Math.max(...xs)+pad,minY=Math.min(...ys)-pad,maxY=Math.max(...ys)+pad,side=Math.max(50,maxX-minX,maxY-minY),cx=(minX+maxX)/2,cy=(minY+maxY)/2;return`${(cx-side/2).toFixed(2)} ${(cy-side/2).toFixed(2)} ${side.toFixed(2)} ${side.toFixed(2)}`}
function selectionJointForPlate(p){return p.bone||p.span?.[1]||p.points?.[0]||'root'}
function decorateRenderedSelection(){const rig=rigs[state.model],parts=new Map(rig.plates.map(p=>[p.id,{type:'plate',jointId:selectionJointForPlate(p)}]));for(const g of generatedGaskets(rig))parts.set(g.id,{type:'gasket',jointId:g.jointId});$$('#mainSvg [id]').forEach(el=>{const part=parts.get(el.id);if(part){el.dataset.selectType=part.type;el.dataset.selectId=el.id;el.dataset.selectJoint=part.jointId}});const visible=rig.joints.filter(j=>!j.helper),dots=$$('#skeletonOverlay .jointDot'),labels=$$('#skeletonOverlay .labelText');visible.forEach((j,i)=>{for(const el of[dots[i],labels[i]])if(el){el.dataset.selectType='joint';el.dataset.selectId=j.id;el.dataset.selectJoint=j.id}});applySelectionUI()}
function applySelectionUI(){const s=state.selection,tokenItems=$$('#mainSvg [data-select-id]'),hasExact=!!s&&tokenItems.some(el=>el.dataset.selectId===s.id);tokenItems.forEach(el=>el.classList.toggle('selectedRigPart',!!s&&(el.dataset.selectId===s.id||(!hasExact&&el.dataset.selectJoint===s.jointId))));$$('#hierarchy [data-package-id]').forEach(el=>el.classList.toggle('selected',!!s&&el.dataset.packageId===s.id));$('#selectionBadge').textContent=s?`${s.type}: ${s.id}`:'nothing selected'}
function selectRigItem(type,id,jointId){state.selection={type,id,jointId:jointId||id};const rig=rigs[state.model],target=rig.joints.some(j=>j.id===state.selection.jointId)?state.selection.jointId:'model';state.transformTarget=target;$('#transformTarget').value=target;refreshTransformUI();applySelectionUI();const row=$(`#hierarchy [data-package-id="${id}"]`);if(row)row.closest('details')?.setAttribute('open','')}
function normalizeHeading(v){return((+v+180)%360+360)%360-180}
function updateViewDockButtons(){$$('.viewBtn[data-view]').forEach(b=>{const presets={top:[90,0],front:[0,180],left:[0,90],right:[0,-90]},p=presets[b.dataset.view];b.classList.toggle('on',state.elev===p[0]&&normalizeHeading(state.az)===normalizeHeading(p[1]))});$$('.viewBtn[data-elevation]').forEach(b=>b.classList.toggle('on',state.elev===+b.dataset.elevation));$$('.viewBtn[data-heading]').forEach(b=>b.classList.toggle('on',normalizeHeading(state.az)===normalizeHeading(b.dataset.heading)))}
function setLiveCamera(elevation,azimuth=state.az){state.elev=elevation;state.az=normalizeHeading(azimuth);$('#elev').value=state.elev;$('#az').value=state.az;$('#elevOut').textContent=state.elev+'°';$('#azOut').textContent=state.az+'°';updatePresetButtons();render();renderMinis()}
function render(){const rig=rigs[state.model],clip=rig.clips[state.clip];$('#mainSvg').setAttribute('viewBox',editorViewBox(rig,state.t,state.clip));$('#mainSvg').innerHTML=svgMarkup(rig,state.t,state.clip);decorateRenderedSelection();updateViewDockButtons();$('#poseBadge').textContent=`${state.clip} · ${(state.t*clip.duration/1000).toFixed(2)}s`;$('#scrub').value=state.t*1000;$('#timeRead').textContent=`${Math.round(state.t*clip.duration)}ms / ${clip.duration}ms`;$('#clipMeta').textContent=`${clip.loop?'loop':'once'} · ${clip.duration}ms · ${clip.easing}${clip.boneLengthPolicy==='preserve'?' · bone lengths locked':''}`;$('#heightStat').textContent=(rig.heightMeters*state.height).toFixed(2);$('#jointStat').textContent=rig.joints.length;$('#plateStat').textContent=rig.plates.length;$('#depthStat').textContent=new Set(rig.plates.map(p=>Math.round(p.zBias))).size;renderFrameInspector(clip);renderEvents(clip);renderSourcePatch();}
function renderEvents(clip){$('#eventTrack').innerHTML=(clip.events||[]).map(e=>`<span class="event" style="left:${e.t*100}%">${e.name}</span>`).join('')}
function currentSourcePatchInspection(){return inspectClipKeyframePatch({sourceModelId:state.model,source:modelSources[state.model],rig:rigs[state.model],clipId:state.clip,time:state.t,jointTransforms:state.jointTransforms[state.model],modelTransform:state.modelTransforms[state.model],baselineModelTransform:defaultModelTransform(state.model),heightScale:state.height,widthScale:state.width})}
function renderSourcePatch(){const result=currentSourcePatchInspection(),status=$('#patchStatus'),text=$('#patchText'),copy=$('#copySourcePatch');status.dataset.status=result.status;status.textContent=result.status==='ready'?`Ready · additive local edits at ${result.patch.context.clipId} keyframe K${result.patch.context.keyframeIndex+1}. Preview overrides remain global until reset.`:result.status==='empty'?'No source patch · make a local joint edit, then select an exact keyframe.':`Cannot create an unambiguous source patch · ${result.message}`;text.textContent=result.patch?JSON.stringify(result.patch,null,2):result.message;copy.disabled=result.status!=='ready'}
function frameTimes(clip=rigs[state.model].clips[state.clip]){return[...new Set(clip.frames.map(f=>f.t))].sort((a,b)=>a-b)}
function stopPlayback(){state.playing=false;$('#playBtn').textContent='Play'}
function selectFrameTime(t){state.t=Math.max(0,Math.min(1,+t));stopPlayback();render()}
function jumpKeyframe(direction){const times=frameTimes(),epsilon=.0001;let target;if(direction<0)target=[...times].reverse().find(t=>t<state.t-epsilon)??times[0];else target=times.find(t=>t>state.t+epsilon)??times.at(-1);selectFrameTime(target)}
function renderFrameInspector(clip){const wrap=$('#frameButtons'),times=frameTimes(clip),signature=`${state.model}|${state.clip}|${times.join(',')}`;if(wrap.dataset.signature!==signature){wrap.dataset.signature=signature;wrap.innerHTML=times.map((t,i)=>{const events=(clip.events||[]).filter(e=>Math.abs(e.t-t)<.0001).map(e=>e.name).join(', ');return`<button class="frameBtn" type="button" data-t="${t}" title="${events||`Keyframe ${i+1}`}">K${i+1}<small>${Math.round(t*clip.duration)}ms</small></button>`}).join('');wrap.querySelectorAll('.frameBtn').forEach(b=>b.onclick=()=>selectFrameTime(b.dataset.t))}wrap.querySelectorAll('.frameBtn').forEach(b=>b.classList.toggle('on',Math.abs(+b.dataset.t-state.t)<.0001))}
function renderMinis(){const rig=rigs[state.model],items=[['top bind','top',0,'bind'],['front bind','front',0,'bind'],['side bind','side',0,'bind'],['far LOD','projected',.5,'idle'],['idle extreme','projected',.5,'idle'],['walk contact L','projected',0,'walk'],['walk contact R','projected',.5,'walk'],['attack impact','projected',.62,'attack']];$('#miniGrid').innerHTML=items.map(([name,v,t,clip])=>`<div class="mini"><svg viewBox="0 0 100 100">${svgMarkup(rig,t,clip,v,{clean:true})}</svg><b>${name}</b></div>`).join('')}
function renderValidationMatrix(){const details=$('#matrixDetails');if(!details.open)return;const rig=rigs[state.model],pkg=rigPayload(),saved={e:state.elev,a:state.az},headings=pkg.directionalBake.headingsDegrees,elevations=pkg.directionalBake.contactSheetElevationsDegrees;let html='';for(const pose of pkg.directionalBake.keyPoses){html+=`<section class="matrixBlock"><h3>${pose.id} · ${pose.clip} @ ${pose.t}</h3>`;for(const elevation of elevations){state.elev=elevation;html+=`<div class="matrixElevation"><strong>${elevation}°</strong>`;for(const heading of headings){state.az=heading;html+=`<div class="matrixCell"><svg viewBox="0 0 100 100">${svgMarkup(rig,pose.t,pose.clip,'projected',{clean:true})}</svg><span>${heading}°</span></div>`}html+='</div>'}html+='</section>'}state.elev=saved.e;state.az=saved.a;$('#matrixGrid').innerHTML=html;const dynamic=directionalValidation(rig,pkg),issues=[...pkg.validation.issues,...dynamic.checks.filter(c=>!c.pass)],status=$('#matrixStatus');status.className='matrixStatus '+(issues.length?'bad':'ok');status.textContent=issues.length?`${issues.length} acceptance issue(s): ${issues.map(i=>i.id).join(', ')}`:`Passed ${dynamic.views} validation projections; showing ${pkg.directionalBake.keyPoses.length*headings.length*elevations.length} contact-sheet views.`;details.dataset.model=state.model}
function renderPackageData(){
  const rig=rigs[state.model],pkg=rigPayload(),dynamic=directionalValidation(rig,pkg);
  $('#jsonText').textContent=JSON.stringify(pkg,null,2);
  const children={};rig.joints.forEach(j=>(children[j.parent||'_']??=[]).push(j));
  const branch=pid=>`<details open><summary>${pid||'root'}</summary>${(children[pid]||[]).map(j=>`<div class="jointRow selectableRigItem" data-package-type="joint" data-package-id="${j.id}" data-package-joint="${j.id}"><span>${j.id} <small>${j.role||''} · ${absoluteSideForJoint(rig,j.id)}</small></span><span class="coord">[${j.bind.map(n=>n.toFixed(2)).join(', ')}]</span></div>${children[j.id]?branch(j.id):''}`).join('')}</details>`;
  const plateRows=pkg.plates.map(p=>{const joint=p.attachment.boneId||p.attachment.jointIds?.at(-1)||'root';return`<div class="packageItem selectableRigItem" data-package-type="plate" data-package-id="${p.id}" data-package-joint="${joint}"><span>${p.id}<small><br>${p.bodyRegion} · ${p.side}</small></span><span>${p.paletteRole}</span></div>`}).join('');
  const gasketRows=pkg.gaskets.map(g=>`<div class="packageItem selectableRigItem" data-package-type="gasket" data-package-id="${g.id}" data-package-joint="${g.jointId}"><span>${g.id}<small><br>joint coverage</small></span><span>${g.paletteRole}</span></div>`).join('');
  const anchorRows=pkg.anchors.map(a=>`<div class="packageItem selectableRigItem" data-package-type="anchor" data-package-id="${a.id}" data-package-joint="${a.boneId||a.bone}"><span>${a.id}<small><br>${a.boneId||a.bone}</small></span><span>anchor</span></div>`).join('');
  $('#hierarchy').innerHTML=`<div class="tree">${branch('_')}<details class="packageSection" open><summary>plates · ${pkg.plates.length}</summary>${plateRows}</details><details class="packageSection"><summary>joint gaskets · ${pkg.gaskets.length}</summary>${gasketRows}</details><details class="packageSection"><summary>anchors · ${pkg.anchors.length}</summary>${anchorRows}</details></div>`;
  $('#clips').innerHTML=`<div class="inherit">${Object.entries(pkg.clips).map(([k,v])=>`<span class="node">${k}<small><br>inherits: ${v.inherits}</small></span>`).join('<span class="arrow">→</span>')}</div><pre style="margin-top:14px">${Object.entries(pkg.clips).map(([k,v])=>`${k.padEnd(8)} ${v.durationMs}ms  ${v.loop?'loop':'once'}  ${v.events.map(e=>e.name+'@'+e.timeNormalized).join(', ')}`).join('\n')}</pre>`;
  const checks=[...pkg.validation.checks,...dynamic.checks];$('#checks').innerHTML=checks.map(c=>`<li class="${c.pass?'':'fail'}"><b>${c.id}</b><br><small>${c.detail}</small></li>`).join('');applySelectionUI();if($('#matrixDetails').open)renderValidationMatrix()
}
function renderData(){const rig=rigs[state.model];$('#jsonText').textContent=JSON.stringify(rigPayload(),null,2);const children={};rig.joints.forEach(j=>(children[j.parent||'_']??=[]).push(j));const branch=(pid)=>`<details open><summary>${pid||'root'}</summary>${(children[pid]||[]).map(j=>`<div class="jointRow"><span>${j.id} <small>${j.role||''}</small></span><span class="coord">[${j.bind.map(n=>n.toFixed(2)).join(', ')}]</span></div>${children[j.id]?branch(j.id):''}`).join('')}</details>`;$('#hierarchy').innerHTML=`<div class="tree">${branch('_')}</div>`;$('#clips').innerHTML=`<div class="inherit">${Object.entries(rig.clips).map(([k,v])=>`<span class="node">${k}<small><br>base: ${v.base}</small></span>`).join('<span class="arrow">→</span>')}</div><pre style="margin-top:14px">${Object.entries(rig.clips).map(([k,v])=>`${k.padEnd(8)} ${v.duration}ms  ${v.loop?'loop':'once'}  ${(v.events||[]).map(e=>e.name+'@'+e.t).join(', ')}`).join('\n')}</pre>`;const checks=[`schema is ${C.schema}`,`${rig.joints.length} stable semantic joint IDs are unique`,'single-parent hierarchy is acyclic','all plate spans overlap both endpoint joints','all rigid plates reference existing bones',...(rig.plates.some(p=>p.points)?['all membrane polygon controls reference semantic joints']:[]),'all mirrors are reciprocal where declared','animation bases resolve to bind or another clip','contact intervals are normalized to [0,1]','camera basis is orthographic and deterministic','canonical authoring camera and named render presets are separate','fixed token framing preserves XYZ translation','joint-local XYZ rotation propagates to descendants','depth ordering uses camera-relative depth',...(rig.family==='biped'?['eye and nose anchors reference semantic facial feature joints']:[]),'accessory anchors opt out of inherited aspect scaling'];$('#checks').innerHTML=checks.map(x=>`<li>${x}</li>`).join('')}
function activeTransform(){if(state.transformTarget==='model')return state.modelTransforms[state.model];return state.jointTransforms[state.model][state.transformTarget]??=( {move:[0,0,0],rot:[0,0,0]} )}
function refreshTransformUI(){const tr=activeTransform();$$('.transformInput').forEach(el=>{const axis=+el.dataset.axis,v=tr[el.dataset.kind][axis];el.value=el.dataset.kind==='move'?Math.round(v*100):Math.round(v);const prefix=el.dataset.kind==='move'?'move':'rot',letter='XYZ'[axis],out=$(`#${prefix}${letter}Out`);out.textContent=el.dataset.kind==='move'?v.toFixed(2):Math.round(v)+'°'})}
function updatePresetButtons(){$$('.presetBtn').forEach(b=>{const p=rigs[state.model].camera.presets?.[b.dataset.preset];b.classList.toggle('on',!!p&&state.elev===p.elevation&&state.az===p.azimuth)})}
function applyCameraPreset(name,announce=true){const p=rigs[state.model].camera.presets?.[name];if(!p)return;state.elev=p.elevation;state.az=p.azimuth;$('#elev').value=state.elev;$('#az').value=state.az;$('#elevOut').textContent=state.elev+'°';$('#azOut').textContent=state.az+'°';updatePresetButtons();render();renderMinis();if(announce)toast(p.label+' camera applied')}
function updateModel(){const rig=rigs[state.model],hasPresets=!!rig.camera.presets,clipOrder=['idle','walk','attack','hit','ko',...Object.keys(rig.clips).filter(k=>!['idle','walk','attack','hit','ko'].includes(k))];state.elev=rig.camera.elevation;state.az=rig.camera.azimuth;state.transformTarget='model';state.selection=null;$('#elev').value=state.elev;$('#az').value=state.az;$('#elevOut').textContent=state.elev+'°';$('#azOut').textContent=state.az+'°';$('#faceSweetSpot').hidden=!hasPresets;$('#humanoidPresets').hidden=!hasPresets;$('#transformTarget').innerHTML=`<option value="model">Entire model</option>${rig.joints.filter(j=>j.id!=='root'&&!j.helper).map(j=>`<option value="${j.id}">${j.id}</option>`).join('')}`;$('#clipSel').innerHTML=clipOrder.map(k=>`<option>${k}</option>`).join('');state.clip='idle';$('#clipSel').value=state.clip;$('#matrixGrid').innerHTML='';delete $('#matrixDetails').dataset.model;updatePresetButtons();refreshTransformUI();render();renderMinis();renderPackageData()}
function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),1200)}
$('#modelSel').onchange=e=>{state.model=e.target.value;updateModel()};
$('#clipSel').onchange=e=>{state.clip=e.target.value;state.t=0;stopPlayback();render();renderMinis()};
$('#playBtn').onclick=()=>{state.playing=!state.playing;$('#playBtn').textContent=state.playing?'Pause':'Play'};
$('#resetBtn').onclick=()=>selectFrameTime(0);
$('#prevFrame').onclick=()=>jumpKeyframe(-1);
$('#nextFrame').onclick=()=>jumpKeyframe(1);
$('#scrub').oninput=e=>{state.t=e.target.value/1000;stopPlayback();render()};
$('#mainSvg').onclick=e=>{const item=e.target.closest('[data-select-id]');if(item)selectRigItem(item.dataset.selectType,item.dataset.selectId,item.dataset.selectJoint)};
$('#hierarchy').onclick=e=>{const item=e.target.closest('[data-package-id]');if(item)selectRigItem(item.dataset.packageType,item.dataset.packageId,item.dataset.packageJoint)};
$$('.viewBtn[data-view]').forEach(b=>b.onclick=()=>{const p={top:[90,0],front:[0,180],left:[0,90],right:[0,-90]}[b.dataset.view];setLiveCamera(...p)});
$$('.viewBtn[data-elevation]').forEach(b=>b.onclick=()=>setLiveCamera(+b.dataset.elevation));
$$('.viewBtn[data-heading]').forEach(b=>b.onclick=()=>setLiveCamera(state.elev,+b.dataset.heading));
$('#transformTarget').onchange=e=>{state.transformTarget=e.target.value;if(state.transformTarget==='model'){state.selection=null;applySelectionUI()}else selectRigItem('joint',state.transformTarget,state.transformTarget);refreshTransformUI()};
$$('.transformInput').forEach(el=>el.oninput=()=>{const tr=activeTransform(),axis=+el.dataset.axis;tr[el.dataset.kind][axis]=el.dataset.kind==='move'?+el.value/100:+el.value;refreshTransformUI();render();renderMinis();renderPackageData()});
$('#resetTransform').onclick=()=>{if(state.transformTarget==='model')state.modelTransforms[state.model]=defaultModelTransform(state.model);else state.jointTransforms[state.model][state.transformTarget]={move:[0,0,0],rot:[0,0,0]};refreshTransformUI();render();renderMinis();renderPackageData()};
for(const[id,key,fmt]of[['elev','elev',v=>v+'°'],['az','az',v=>v+'°'],['heightScale','height',v=>(v/100).toFixed(2)+'×'],['widthScale','width',v=>(v/100).toFixed(2)+'×']])$('#'+id).oninput=e=>{state[key]=id.includes('Scale')?e.target.value/100:+e.target.value;$('#'+(id==='heightScale'?'heightOut':id==='widthScale'?'widthOut':id==='elev'?'elevOut':'azOut')).textContent=fmt(+e.target.value);updatePresetButtons();render();renderMinis()};
$('#bones').onchange=e=>{state.bones=e.target.checked;render()};
$('#contacts').onchange=e=>{state.contacts=e.target.checked;render()};
$$('.presetBtn').forEach(b=>b.onclick=()=>applyCameraPreset(b.dataset.preset));
$('#faceSweetSpot').onclick=()=>applyCameraPreset('faceReadable');
$('#matrixDetails').ontoggle=()=>renderValidationMatrix();
$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.toggle('on',x===b));$$('.dataPage').forEach(x=>x.classList.toggle('on',x.id===b.dataset.tab))});
$('#copyJson').onclick=async()=>{await navigator.clipboard.writeText(JSON.stringify(rigPayload(),null,2));toast('Rig JSON copied')};
$('#downloadJson').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(rigPayload(),null,2)],{type:'application/json'}));a.download=rigs[state.model].id+'.paper-rig.json';a.click();URL.revokeObjectURL(a.href);toast('Rig JSON saved')};
$('#copySvg').onclick=async()=>{await navigator.clipboard.writeText(exportedSvg());toast('Projected SVG copied')};
$('#downloadSvg').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([exportedSvg()],{type:'image/svg+xml'}));a.download=rigs[state.model].id+'.svg';a.click();URL.revokeObjectURL(a.href);toast('SVG saved')};
$('#copySourcePatch').onclick=async()=>{const result=currentSourcePatchInspection();if(result.status!=='ready')return;await navigator.clipboard.writeText(JSON.stringify(result.patch,null,2)+'\n');toast('Source patch copied')};
$('#copyHandoff').onclick=async()=>{await navigator.clipboard.writeText($('#handoffText').textContent);toast('Maintainer handoff copied')};
function tick(now){if(state.playing&&now-state.lastPaint>=32){const clip=rigs[state.model].clips[state.clip];state.t=(state.t+(now-state.lastPaint)/clip.duration)%(clip.loop?1:1.00001);if(!clip.loop&&state.t>=1){state.t=1;state.playing=false;$('#playBtn').textContent='Play'}render();state.lastPaint=now}requestAnimationFrame(tick)}
updateModel();
document.documentElement.dataset.rigReady='true';
requestAnimationFrame(tick);
