// Legacy creature builders, extracted verbatim from paper-rig-workbench.html.
// A script fragment (NOT a standalone module): it is concatenated after the
// schema + compiler bundle by `rig build-workbench`, and defines the global
// `rigs` table the workbench UI drives. Creatures migrate out of here into
// rigs/models/*.json over time.
/* eslint-disable */
const horse={...C,id:'horseBase',family:'quadruped',heightMeters:1.62,tokenScale:28,tokenGroundY:68,surfaceConvention:{outward:'+z',groundPlane:'z=0',canonicalModelRotation:[0,0,0]},camera:{type:'orthographic',direction:[0,0,-1],elevation:90,azimuth:0,preset:'true-overhead',orientation:'camera is above +Z and looks straight down -Z; head/forward +X projects toward token top; tail/rear projects toward token bottom',framing:'fixed scale with ground origin at token [50,68]',depthOrder:'far-to-near camera depth; higher +Z surfaces render nearer; stable semantic-id tie break'},
 joints:[joint('root',null,V(0,0,0),{role:'root'}),joint('pelvis','root',V(-.36,0,.78),{role:'body'}),joint('chest','pelvis',V(.72,0,.24),{role:'body'}),joint('neckBase','chest',V(.32,0,.22),{role:'neck'}),joint('neckTip','neckBase',V(.30,0,.34),{role:'neck',bendAxis:V(0,1,0),limits:[-35,55]}),joint('head','neckTip',V(.27,0,.08),{role:'head'}),joint('muzzle','head',V(.18,0,-.04),{role:'head'}),
 joint('nearFrontHip','chest',V(-.10,.25,-.02),{role:'limb',mirror:'farFrontHip',diagonal:'farRearHip',ik:'nearFrontLeg'}),joint('nearFrontKnee','nearFrontHip',V(.02,0,-.48),{role:'limb',mirror:'farFrontKnee',diagonal:'farRearKnee',bendAxis:V(0,1,0),limits:[-35,115]}),joint('nearFrontHoof','nearFrontKnee',V(.05,0,-.45),{role:'limb',mirror:'farFrontHoof',diagonal:'farRearHoof'}),joint('farFrontHip','chest',V(-.10,-.25,-.02),{role:'limb',mirror:'nearFrontHip',diagonal:'nearRearHip',ik:'farFrontLeg'}),joint('farFrontKnee','farFrontHip',V(.02,0,-.48),{role:'limb',mirror:'nearFrontKnee',diagonal:'nearRearKnee',bendAxis:V(0,1,0),limits:[-35,115]}),joint('farFrontHoof','farFrontKnee',V(.05,0,-.45),{role:'limb',mirror:'nearFrontHoof',diagonal:'nearRearHoof'}),
 joint('nearRearHip','pelvis',V(-.08,.26,-.01),{role:'limb',mirror:'farRearHip',diagonal:'farFrontHip',ik:'nearRearLeg'}),joint('nearRearKnee','nearRearHip',V(-.10,0,-.48),{role:'limb',mirror:'farRearKnee',diagonal:'farFrontKnee',bendAxis:V(0,1,0),limits:[-115,35]}),joint('nearRearHoof','nearRearKnee',V(.06,0,-.44),{role:'limb',mirror:'farRearHoof',diagonal:'farFrontHoof'}),joint('farRearHip','pelvis',V(-.08,-.26,-.01),{role:'limb',mirror:'nearRearHip',diagonal:'nearFrontHip',ik:'farRearLeg'}),joint('farRearKnee','farRearHip',V(-.10,0,-.48),{role:'limb',mirror:'nearRearKnee',diagonal:'nearFrontKnee',bendAxis:V(0,1,0),limits:[-115,35]}),joint('farRearHoof','farRearKnee',V(.06,0,-.44),{role:'limb',mirror:'nearRearHoof',diagonal:'nearFrontHoof'}),joint('tailBase','pelvis',V(-.28,0,.08),{role:'tail'}),joint('tailTip','tailBase',V(-.35,0,-.18),{role:'tail'})],
 plates:[plate('castShadow','root','ellipse',[1.55,.68],'shadow',-99),spanPlate('torsoPlate','pelvis','chest',.66,'body',3),plate('pelvisPlate','pelvis','ellipse',[.68,.62],'body',3.1),spanPlate('withersPlate','chest','neckBase',.50,'body',3.8),spanPlate('neckPlate','neckBase','neckTip',.26,'body',4),spanPlate('headConnectorPlate','neckTip','head',.30,'body',4.8),plate('headPlate','head','ellipse',[.40,.54],'body',5),spanPlate('muzzleConnectorPlate','head','muzzle',.23,'accent',5.05),plate('muzzlePlate','muzzle','ellipse',[.27,.36],'accent',5.1),...['nearFront','farFront','nearRear','farRear'].flatMap(n=>[spanPlate(n+'UpperPlate',n+'Hip',n+'Knee',.17,'body',1),spanPlate(n+'LowerPlate',n+'Knee',n+'Hoof',.14,'body',1.2),plate(n+'HoofPlate',n+'Hoof','ellipse',[.20,.15],'accent',0)]),spanPlate('tailConnectorPlate','pelvis','tailBase',.15,'accent',1.9),spanPlate('tailPlate','tailBase','tailTip',.13,'accent',2)],
 anchors:[{id:'headgearAnchor',bone:'head',offset:V(0,0,.18),inheritScale:false},{id:'saddleBackAnchor',bone:'chest',offset:V(-.05,0,.32),inheritScale:false}],
 clips:{idleA:{base:'bind',duration:1800,easing:'ease-in-out',loop:true,frames:[{t:0,poses:{head:[0,0,.015]}},{t:.5,poses:{head:[.015,0,-.01],chest:[0,0,.012]}},{t:1,poses:{head:[0,0,.015]}}],contacts:['nearFrontHoof','farFrontHoof','nearRearHoof','farRearHoof']},walkA:{base:'idleA',duration:950,easing:'linear',loop:true,frames:[{t:0,poses:{nearFrontHoof:[.22,0,.07],farRearHoof:[.20,0,.07],farFrontHoof:[-.18,0,0],nearRearHoof:[-.18,0,0]}},{t:.5,poses:{nearFrontHoof:[-.18,0,0],farRearHoof:[-.18,0,0],farFrontHoof:[.22,0,.07],nearRearHoof:[.20,0,.07]}},{t:1,poses:{nearFrontHoof:[.22,0,.07],farRearHoof:[.20,0,.07],farFrontHoof:[-.18,0,0],nearRearHoof:[-.18,0,0]}}],contactIntervals:[{ids:['farFrontHoof','nearRearHoof'],from:0,to:.48},{ids:['nearFrontHoof','farRearHoof'],from:.5,to:.98}],events:[{t:0,name:'diagonalA-plant'},{t:.5,name:'diagonalB-plant'}]},attack:{base:'idleA',duration:720,easing:'cubic-bezier(.2,.8,.2,1)',loop:false,frames:[{t:0,poses:{}},{t:.62,poses:{neckTip:[.26,0,.02],head:[.32,0,-.04],chest:[.07,0,.02]}},{t:1,poses:{}}],contacts:['nearFrontHoof','farFrontHoof','nearRearHoof','farRearHoof'],events:[{t:.62,name:'impact'},{t:.8,name:'release'}]}}};
const humanoid={...C,id:'humanoidBase',family:'biped',heightMeters:1.78,tokenScale:31,tokenGroundY:78,surfaceConvention:{outward:'+z',faceNormal:'+x',groundPlane:'z=0',canonicalModelRotation:[0,0,0]},camera:{type:'orthographic',direction:[0,0,-1],elevation:90,azimuth:0,preset:'canonicalTop',presets:{canonicalTop:{label:'Top',elevation:90,azimuth:0,direction:[0,0,-1]},faceReadable:{label:'Face 58°',elevation:58,azimuth:180,direction:[-0.530,0,-0.848],note:'top-down with forward face surface visible'},headOn:{label:'Head-on',elevation:0,azimuth:180,direction:[-1,0,0],note:'orthographic view normal to the +X face plane'}},orientation:'canonical authoring view is straight down -Z with zero model rotation; +X remains the face direction',framing:'fixed scale with ground origin at token [50,78]',depthOrder:'far-to-near camera depth; stable semantic-id tie break'},
 joints:[joint('root',null,V(0,0,0),{role:'root'}),joint('hips','root',V(0,0,.88),{role:'body'}),joint('spine','hips',V(0,0,.34),{role:'body'}),joint('shoulders','spine',V(.02,0,.27),{role:'body'}),joint('neck','shoulders',V(.02,0,.13),{role:'neck'}),joint('head','neck',V(.02,0,.20),{role:'head'}),joint('face','head',V(.13,0,-.01),{role:'head',facing:'+x'}),joint('leftEye','face',V(.035,.075,.055),{role:'faceFeature',mirror:'rightEye',helper:true}),joint('rightEye','face',V(.035,-.075,.055),{role:'faceFeature',mirror:'leftEye',helper:true}),joint('nose','face',V(.065,0,-.015),{role:'faceFeature',protrusionAxis:'+x',helper:true}),
 joint('nearHip','hips',V(0,.14,-.02),{role:'limb',mirror:'farHip',diagonal:'farShoulder',ik:'nearLeg'}),joint('nearKnee','nearHip',V(.02,0,-.46),{role:'limb',mirror:'farKnee',bendAxis:V(0,1,0),limits:[0,145]}),joint('nearFoot','nearKnee',V(-.04,0,-.42),{role:'limb',mirror:'farFoot',preferredLean:'slightly rearward'}),joint('farHip','hips',V(0,-.14,-.02),{role:'limb',mirror:'nearHip',diagonal:'nearShoulder',ik:'farLeg'}),joint('farKnee','farHip',V(.02,0,-.46),{role:'limb',mirror:'nearKnee',bendAxis:V(0,1,0),limits:[0,145]}),joint('farFoot','farKnee',V(-.04,0,-.42),{role:'limb',mirror:'nearFoot',preferredLean:'slightly rearward'}),
 joint('nearShoulder','shoulders',V(0,.28,0),{role:'limb',mirror:'farShoulder',diagonal:'farHip'}),joint('nearElbow','nearShoulder',V(.05,.13,-.28),{role:'limb',mirror:'farElbow',bendAxis:V(0,0,1),limits:[0,155]}),joint('nearHand','nearElbow',V(.18,-.03,-.27),{role:'limb',mirror:'farHand'}),joint('farShoulder','shoulders',V(0,-.28,0),{role:'limb',mirror:'nearShoulder',diagonal:'nearHip'}),joint('farElbow','farShoulder',V(.05,-.13,-.28),{role:'limb',mirror:'nearElbow',bendAxis:V(0,0,-1),limits:[0,155]}),joint('farHand','farElbow',V(.18,.03,-.27),{role:'limb',mirror:'nearHand'})],
 plates:[plate('castShadow','root','ellipse',[.72,.42],'shadow',-99),spanPlate('pelvisSpinePlate','hips','spine',.52,'body',3),spanPlate('chestPlate','spine','shoulders',.64,'body',3.5),plate('shoulderPlate','shoulders','ellipse',[.74,.32],'accent',4.5),spanPlate('neckPlate','shoulders','neck',.22,'body',5),spanPlate('headConnectorPlate','neck','head',.28,'body',5.2),plate('headPlate','head','ellipse',[.38,.45],'body',5.5),{...plate('leftEyePlate','leftEye','disc',[.07,.07],'eye',6.2),surfaceNormal:[1,0,0],planeAxes:['+y','+z']},{...plate('rightEyePlate','rightEye','disc',[.07,.07],'eye',6.2),surfaceNormal:[1,0,0],planeAxes:['+y','+z']},{...plate('nosePlate','nose','roundedTip',[.105,.12],'nose',6.3),surfaceNormal:[1,0,0],planeAxes:['+y','+z']},...['near','far'].flatMap(n=>[spanPlate(n+'ThighPlate',n+'Hip',n+'Knee',.18,'body',1),spanPlate(n+'ShinPlate',n+'Knee',n+'Foot',.15,'body',1.2),plate(n+'FootPlate',n+'Foot','ellipse',[.22,.14],'accent',0),spanPlate(n+'BicepPlate',n+'Shoulder',n+'Elbow',.15,'body',4),spanPlate(n+'ForearmPlate',n+'Elbow',n+'Hand',.13,'body',4.2),plate(n+'HandPlate',n+'Hand','ellipse',[.17,.14],'accent',4.3)])],
 anchors:[{id:'nearGripAnchor',bone:'nearHand',offset:V(.08,0,0),inheritScale:false},{id:'farGripAnchor',bone:'farHand',offset:V(.08,0,0),inheritScale:false},{id:'faceAnchor',bone:'face',offset:V(.03,0,0),forward:'+x',inheritScale:false},{id:'leftEyeAnchor',bone:'leftEye',offset:V(0,0,0),role:'eye',counterpart:'rightEyeAnchor',inheritScale:false},{id:'rightEyeAnchor',bone:'rightEye',offset:V(0,0,0),role:'eye',counterpart:'leftEyeAnchor',inheritScale:false},{id:'noseAnchor',bone:'nose',offset:V(0,0,0),role:'nose',protrusionAxis:'+x',inheritScale:false},{id:'headgearAnchor',bone:'head',offset:V(0,0,.22),inheritScale:false},{id:'backAnchor',bone:'shoulders',offset:V(-.04,0,.08),inheritScale:false}],
 clips:{idleA:{base:'bind',duration:1800,easing:'ease-in-out',loop:true,frames:[{t:0,poses:{head:[0,0,.01]}},{t:.5,poses:{head:[0,0,-.01],shoulders:[.01,0,.01]}},{t:1,poses:{head:[0,0,.01]}}],contacts:['nearFoot','farFoot']},walkA:{base:'idleA',duration:900,easing:'linear',loop:true,frames:[{t:0,poses:{nearFoot:[.18,0,.08],farFoot:[-.14,0,.015],nearHand:[-.08,0,0],farHand:[.08,0,0]}},{t:.5,poses:{nearFoot:[-.14,0,.015],farFoot:[.18,0,.08],nearHand:[.08,0,0],farHand:[-.08,0,0]}},{t:1,poses:{nearFoot:[.18,0,.08],farFoot:[-.14,0,.015],nearHand:[-.08,0,0],farHand:[.08,0,0]}}],contactIntervals:[{ids:['farFoot'],from:0,to:.48},{ids:['nearFoot'],from:.5,to:.98}],events:[{t:0,name:'near-step'},{t:.5,name:'far-step'}]},attack:{base:'idleA',duration:620,easing:'cubic-bezier(.2,.8,.2,1)',loop:false,frames:[{t:0,poses:{}},{t:.62,poses:{nearElbow:[.08,-.12,.05],nearHand:[.48,-.34,.13],shoulders:[.06,-.03,0]}},{t:1,poses:{}}],contacts:['nearFoot','farFoot'],events:[{t:.62,name:'impact'},{t:.83,name:'release'}]}}};
const topCamera=(groundY)=>({type:'orthographic',direction:[0,0,-1],elevation:90,azimuth:0,preset:'canonicalTop',orientation:'camera is above +Z and looks straight down -Z; +X points toward token top',framing:`fixed scale with ground origin at token [50,${groundY}]`,depthOrder:'far-to-near camera depth; stable semantic-id tie break'});
const clipPack=({idle={},moveA={},moveB={},attack={},contacts=[],intervals=[],moveDuration=960,attackDuration=680,moveEventA='phase-a',moveEventB='phase-b'})=>({
  idleA:{base:'bind',duration:1800,easing:'ease-in-out',loop:true,frames:[{t:0,poses:{}},{t:.5,poses:idle},{t:1,poses:{}}],contacts},
  walkA:{base:'idleA',duration:moveDuration,easing:'linear',loop:true,frames:[{t:0,poses:moveA},{t:.5,poses:moveB},{t:1,poses:moveA}],contactIntervals:intervals,events:[{t:0,name:moveEventA},{t:.5,name:moveEventB}]},
  attack:{base:'idleA',duration:attackDuration,easing:'cubic-bezier(.2,.8,.2,1)',loop:false,frames:[{t:0,poses:{}},{t:.62,poses:attack},{t:1,poses:{}}],contacts,events:[{t:.62,name:'impact'},{t:.84,name:'release'}]}
});
const templateRig=({id,family,archetypes,height,scale,groundY=72,joints,plates,anchors=[],clips,profile={}})=>({...C,id,family,archetypes,heightMeters:height,tokenScale:scale,tokenGroundY:groundY,surfaceConvention:{outward:'+z',groundPlane:'z=0',canonicalModelRotation:[0,0,0]},camera:topCamera(groundY),profile,joints,plates,anchors,clips});
const cloneBipedClips=(sx,sy,sz)=>Object.fromEntries(Object.entries(humanoid.clips).map(([name,c])=>[name,{...c,frames:c.frames.map(f=>({t:f.t,poses:Object.fromEntries(Object.entries(f.poses).map(([id,v])=>[id,V(v[0]*sx,v[1]*sy,v[2]*sz)]))})),contacts:c.contacts?[...c.contacts]:undefined,contactIntervals:c.contactIntervals?.map(x=>({...x,ids:[...x.ids]})),events:c.events?.map(x=>({...x}))}]));
function bipedVariant({id,archetypes,height,sx,sy,sz,headScale,scale=31,profile={},tail=false}){const omitted=new Set(['face','leftEye','rightEye','nose']),joints=humanoid.joints.filter(j=>!omitted.has(j.id)).map(j=>({...j,bind:V(j.bind[0]*sx,j.bind[1]*sy,j.bind[2]*sz)}));const plates=humanoid.plates.filter(p=>!['leftEyePlate','rightEyePlate','nosePlate'].includes(p.id)).map(p=>{const k=p.id==='headPlate'?headScale:p.role==='shadow'?Math.max(sx,sy):(p.span?(sy+sz)/2:sy);return{...p,size:p.size.map(v=>v*k),span:p.span?[...p.span]:undefined}});const anchors=humanoid.anchors.filter(a=>!['faceAnchor','leftEyeAnchor','rightEyeAnchor','noseAnchor'].includes(a.id)).map(a=>({...a,offset:V(a.offset[0]*sx,a.offset[1]*sy,a.offset[2]*sz)}));const clips=cloneBipedClips(sx,sy,sz);if(tail){joints.push(joint('tailBase','hips',V(-.18,0,.04),{role:'tail'}),joint('tailMid','tailBase',V(-.36,0,-.06),{role:'tail'}),joint('tailTip','tailMid',V(-.34,0,-.10),{role:'tail',ik:'tailChain'}));plates.push(spanPlate('tailConnectorPlate','hips','tailBase',.22,'body',2.8),spanPlate('tailMidPlate','tailBase','tailMid',.17,'accent',2.5),spanPlate('tailTipPlate','tailMid','tailTip',.11,'accent',2.3));anchors.push({id:'tailTipAnchor',bone:'tailTip',offset:V(-.05,0,0),inheritScale:false});clips.idleA.frames[1].poses.tailTip=V(0,.05,.01);clips.walkA.frames[0].poses.tailMid=V(0,.06,.01);clips.walkA.frames[0].poses.tailTip=V(0,.11,.02);clips.walkA.frames[1].poses.tailMid=V(0,-.06,.01);clips.walkA.frames[1].poses.tailTip=V(0,-.11,.02);clips.walkA.frames[2].poses.tailMid=V(0,.06,.01);clips.walkA.frames[2].poses.tailTip=V(0,.11,.02);clips.attack.frames[1].poses.tailMid=V(0,-.10,.02);clips.attack.frames[1].poses.tailTip=V(0,-.20,.04)}return{...C,id,family:'bipedVariant',variantOf:'humanoidBase',archetypes,heightMeters:height,tokenScale:scale,tokenGroundY:78,surfaceConvention:{...humanoid.surfaceConvention},camera:{...humanoid.camera,presets:Object.fromEntries(Object.entries(humanoid.camera.presets).map(([k,v])=>[k,{...v,direction:[...v.direction]}]))},profile:{...profile,facialFeatures:'omitted by template request'},joints,plates,anchors,clips}}
const tinyBiped=bipedVariant({id:'tinyBipedBase',archetypes:['gnome','halfling','tiny humanoid'],height:.96,sx:.58,sy:.78,sz:.56,headScale:.93,scale:31,profile:{proportions:'short limbs, relatively large head',sizeClass:'tiny'}});
const stoutBiped=bipedVariant({id:'stoutBipedBase',archetypes:['dwarf','stout golem','stocky humanoid'],height:1.34,sx:.76,sy:1.24,sz:.76,headScale:1.02,scale:31,profile:{proportions:'shorter, broader torso and limbs',sizeClass:'medium-stout'}});
const tailedBiped=bipedVariant({id:'tailedBipedBase',archetypes:['dragonborn'],height:2.02,sx:1.08,sy:1.05,sz:1.10,headScale:1.08,scale:29,tail:true,profile:{proportions:'tall broad biped with articulated counterbalance tail',sizeClass:'large',facialFeatures:'snout plus paired modular horn mounts'}});
tailedBiped.joints.push(joint('snout','head',V(.18,0,-.02),{role:'snout',facing:'+x'}),joint('nearHornMount','head',V(-.03,.13,.15),{role:'accessoryAnchor',mirror:'farHornMount'}),joint('farHornMount','head',V(-.03,-.13,.15),{role:'accessoryAnchor',mirror:'nearHornMount'}));
tailedBiped.plates.push(spanPlate('snoutConnectorPlate','head','snout',.22,'body',5.7),plate('snoutPlate','snout','ellipse',[.27,.25],'accent',5.8),plate('nearHornMountPlate','nearHornMount','ellipse',[.12,.12],'accent',6),plate('farHornMountPlate','farHornMount','ellipse',[.12,.12],'accent',6));
tailedBiped.anchors.push({id:'snoutTipAnchor',bone:'snout',offset:V(.08,0,0),inheritScale:false},{id:'nearHornAnchor',bone:'nearHornMount',offset:V(0,0,0),counterpart:'farHornAnchor',inheritScale:false},{id:'farHornAnchor',bone:'farHornMount',offset:V(0,0,0),counterpart:'nearHornAnchor',inheritScale:false});
tailedBiped.profile.facialFeatures='snout plus paired modular horn mounts';
const blob=templateRig({id:'blobBase',family:'blob',archetypes:['slime','mud elemental','egg','will-o-wisp','gelatinous cube','amoeba'],height:.68,scale:43,groundY:72,profile:{baseNodes:[1,3],arms:'optional',silhouette:'stacked deformable mass'},
  joints:[joint('root',null,V(0,0,0),{role:'root'}),joint('baseMass','root',V(-.08,0,.16),{role:'body'}),joint('middleMass','baseMass',V(.12,0,.22),{role:'body'}),joint('topMass','middleMass',V(.12,0,.22),{role:'body'}),joint('nearArm','middleMass',V(.02,.27,.02),{role:'limb',mirror:'farArm'}),joint('nearHand','nearArm',V(.08,.25,-.05),{role:'limb',mirror:'farHand'}),joint('farArm','middleMass',V(.02,-.27,.02),{role:'limb',mirror:'nearArm'}),joint('farHand','farArm',V(.08,-.25,-.05),{role:'limb',mirror:'nearHand'})],
  plates:[plate('castShadow','root','ellipse',[.86,.58],'shadow',-99),plate('baseMassPlate','baseMass','ellipse',[.72,.62],'body',1),plate('middleMassPlate','middleMass','ellipse',[.62,.56],'body',2),plate('topMassPlate','topMass','ellipse',[.44,.40],'accent',3),spanPlate('nearArmPlate','nearArm','nearHand',.16,'body',2.2),plate('nearHandPlate','nearHand','ellipse',[.19,.17],'accent',2.3),spanPlate('farArmPlate','farArm','farHand',.16,'body',2.2),plate('farHandPlate','farHand','ellipse',[.19,.17],'accent',2.3)],
  anchors:[{id:'crownAnchor',bone:'topMass',offset:V(0,0,.18),inheritScale:false},{id:'nearGripAnchor',bone:'nearHand',offset:V(.06,0,0),inheritScale:false},{id:'farGripAnchor',bone:'farHand',offset:V(.06,0,0),inheritScale:false}],
  clips:clipPack({idle:{topMass:[-.03,0,.04],middleMass:[.02,0,-.02]},moveA:{baseMass:[.08,.03,0],topMass:[-.05,-.04,.02]},moveB:{baseMass:[-.08,-.03,0],topMass:[.05,.04,.02]},attack:{nearHand:[.32,-.18,.06],middleMass:[.08,0,.02]},contacts:['root'],intervals:[{ids:['root'],from:0,to:1}],moveEventA:'squish-a',moveEventB:'squish-b'})});
const quadrupedJoints=[joint('root',null,V(0,0,0),{role:'root'}),joint('pelvis','root',V(-.34,0,.62),{role:'body'}),joint('chest','pelvis',V(.66,0,.12),{role:'body'}),joint('neck','chest',V(.25,0,.12),{role:'neck'}),joint('head','neck',V(.28,0,.04),{role:'head'}),joint('nearHornMount','head',V(-.02,.12,.14),{role:'accessoryAnchor',mirror:'farHornMount'}),joint('farHornMount','head',V(-.02,-.12,.14),{role:'accessoryAnchor',mirror:'nearHornMount'}),joint('tailBase','pelvis',V(-.28,0,.03),{role:'tail'}),joint('tailTip','tailBase',V(-.34,0,-.12),{role:'tail'}),
  joint('nearFrontHip','chest',V(-.05,.22,-.02),{role:'limb',mirror:'farFrontHip',diagonal:'farRearHip'}),joint('nearFrontKnee','nearFrontHip',V(.02,0,-.32),{role:'limb',mirror:'farFrontKnee',diagonal:'farRearKnee',bendAxis:V(0,1,0),limits:[-30,120]}),joint('nearFrontPaw','nearFrontKnee',V(.04,0,-.31),{role:'limb',mirror:'farFrontPaw',diagonal:'farRearPaw',ik:'nearFrontLeg'}),joint('farFrontHip','chest',V(-.05,-.22,-.02),{role:'limb',mirror:'nearFrontHip',diagonal:'nearRearHip'}),joint('farFrontKnee','farFrontHip',V(.02,0,-.32),{role:'limb',mirror:'nearFrontKnee',diagonal:'nearRearKnee',bendAxis:V(0,1,0),limits:[-30,120]}),joint('farFrontPaw','farFrontKnee',V(.04,0,-.31),{role:'limb',mirror:'nearFrontPaw',diagonal:'nearRearPaw',ik:'farFrontLeg'}),
  joint('nearRearHip','pelvis',V(-.04,.23,-.02),{role:'limb',mirror:'farRearHip',diagonal:'farFrontHip'}),joint('nearRearKnee','nearRearHip',V(-.05,0,-.32),{role:'limb',mirror:'farRearKnee',diagonal:'farFrontKnee',bendAxis:V(0,1,0),limits:[-120,30]}),joint('nearRearPaw','nearRearKnee',V(.03,0,-.30),{role:'limb',mirror:'farRearPaw',diagonal:'farFrontPaw',ik:'nearRearLeg'}),joint('farRearHip','pelvis',V(-.04,-.23,-.02),{role:'limb',mirror:'nearRearHip',diagonal:'nearFrontHip'}),joint('farRearKnee','farRearHip',V(-.05,0,-.32),{role:'limb',mirror:'nearRearKnee',diagonal:'nearFrontKnee',bendAxis:V(0,1,0),limits:[-120,30]}),joint('farRearPaw','farRearKnee',V(.03,0,-.30),{role:'limb',mirror:'nearRearPaw',diagonal:'nearFrontPaw',ik:'farRearLeg'})];
const quadruped=templateRig({id:'quadrupedBase',family:'quadruped',archetypes:['generic canid','lion','raccoon','bear'],height:1.05,scale:29,groundY:70,profile:{torso:'medium',neck:'short',locomotion:'diagonal gait',modularHornMounts:['nearHornMount','farHornMount']},joints:quadrupedJoints,
  plates:[plate('castShadow','root','ellipse',[1.34,.70],'shadow',-99),spanPlate('torsoPlate','pelvis','chest',.58,'body',3),plate('pelvisPlate','pelvis','ellipse',[.58,.54],'body',3.1),spanPlate('neckPlate','chest','neck',.34,'body',4),spanPlate('headConnectorPlate','neck','head',.30,'body',4.7),plate('headPlate','head','ellipse',[.38,.42],'accent',5),spanPlate('tailPlate','tailBase','tailTip',.13,'accent',2),...['nearFront','farFront','nearRear','farRear'].flatMap(n=>[spanPlate(n+'UpperPlate',n+'Hip',n+'Knee',.17,'body',1),spanPlate(n+'LowerPlate',n+'Knee',n+'Paw',.14,'body',1.2),plate(n+'PawPlate',n+'Paw','ellipse',[.20,.15],'accent',0)])],
  anchors:[{id:'collarAnchor',bone:'neck',offset:V(0,0,.14),inheritScale:false},{id:'backAnchor',bone:'chest',offset:V(-.12,0,.25),inheritScale:false},{id:'nearHornAnchor',bone:'nearHornMount',offset:V(0,0,0),counterpart:'farHornAnchor',moduleType:'horn',inheritScale:false},{id:'farHornAnchor',bone:'farHornMount',offset:V(0,0,0),counterpart:'nearHornAnchor',moduleType:'horn',inheritScale:false}],
  clips:clipPack({idle:{head:[.01,0,.02],tailTip:[0,.04,0]},moveA:{nearFrontPaw:[.17,0,.06],farRearPaw:[.15,0,.05],farFrontPaw:[-.13,0,0],nearRearPaw:[-.13,0,0]},moveB:{nearFrontPaw:[-.13,0,0],farRearPaw:[-.13,0,0],farFrontPaw:[.17,0,.06],nearRearPaw:[.15,0,.05]},attack:{head:[.25,0,.04],neck:[.16,0,.02]},contacts:['nearFrontPaw','farFrontPaw','nearRearPaw','farRearPaw'],intervals:[{ids:['farFrontPaw','nearRearPaw'],from:0,to:.48},{ids:['nearFrontPaw','farRearPaw'],from:.5,to:.98}]})});
const cloneClipsScaled=(rig,sx,sy,sz)=>Object.fromEntries(Object.entries(rig.clips).map(([name,c])=>[name,{...c,frames:c.frames.map(f=>({t:f.t,poses:Object.fromEntries(Object.entries(f.poses).map(([id,v])=>[id,V(v[0]*sx,v[1]*sy,v[2]*sz)]))})),contacts:c.contacts?[...c.contacts]:undefined,contactIntervals:c.contactIntervals?.map(x=>({...x,ids:[...x.ids]})),events:c.events?.map(x=>({...x}))}]));
function quadrupedVariant({id,archetypes,height,scale,groundY=70,sx=1,sy=1,sz=1,thickness=1,profile={},jointTweaks={},plateTweaks={}}){const joints=quadruped.joints.map(j=>({...j,bind:jointTweaks[j.id]?[...jointTweaks[j.id]]:V(j.bind[0]*sx,j.bind[1]*sy,j.bind[2]*sz)})),plates=quadruped.plates.map(p=>{let size=p.span?p.size.map(v=>v*thickness):p.size.map((v,i)=>v*(i? sx:sy));if(plateTweaks[p.id])size=[...plateTweaks[p.id]];return{...p,size,span:p.span?[...p.span]:undefined}}),anchors=quadruped.anchors.map(a=>({...a,offset:V(a.offset[0]*sx,a.offset[1]*sy,a.offset[2]*sz)})),clips=cloneClipsScaled(quadruped,sx,sy,sz);return{...templateRig({id,family:'quadrupedVariant',archetypes,height,scale,groundY,joints,plates,anchors,clips,profile:{...profile,locomotion:'diagonal gait',modularHornMounts:['nearHornMount','farHornMount']}}),variantOf:'quadrupedBase'}}
function tuneQuadrupedLimbs(rig,upper,lower,paw){for(const p of rig.plates){if(p.id.endsWith('UpperPlate'))p.size=[upper];if(p.id.endsWith('LowerPlate'))p.size=[lower];if(p.id.endsWith('PawPlate'))p.size=[...paw]}}
function addMuzzle(rig,{length=.22,width=.24,height=.28,id='muzzle',z=0}={}){rig.joints.push(joint(id,'head',V(length,0,z),{role:'snout',facing:'+x'}));rig.plates.push(spanPlate(id+'ConnectorPlate','head',id,width,'body',5.3),plate(id+'Plate',id,'ellipse',[width,height],'accent',5.4));rig.anchors.push({id:id+'TipAnchor',bone:id,offset:V(length*.25,0,0),inheritScale:false})}
function addPairedEars(rig,{baseX=-.04,baseY=.11,baseZ=.09,tipX=-.10,tipY=.13,tipZ=.08,width=.11,style='ear'}={}){rig.joints.push(joint('nearEarBase','head',V(baseX,baseY,baseZ),{role:'ear',mirror:'farEarBase'}),joint('nearEarTip','nearEarBase',V(tipX,tipY,tipZ),{role:'ear',mirror:'farEarTip'}),joint('farEarBase','head',V(baseX,-baseY,baseZ),{role:'ear',mirror:'nearEarBase'}),joint('farEarTip','farEarBase',V(tipX,-tipY,tipZ),{role:'ear',mirror:'nearEarTip'}));rig.plates.push(spanPlate('nearEarPlate','nearEarBase','nearEarTip',width,'accent',5.5),spanPlate('farEarPlate','farEarBase','farEarTip',width,'accent',5.5));rig.anchors.push({id:'nearEarTipAnchor',bone:'nearEarTip',offset:V(0,0,0),counterpart:'farEarTipAnchor',style,inheritScale:false},{id:'farEarTipAnchor',bone:'farEarTip',offset:V(0,0,0),counterpart:'nearEarTipAnchor',style,inheritScale:false})}
const rhino=quadrupedVariant({id:'rhinoBase',archetypes:['rhinoceros','armored megafauna'],height:1.75,scale:18,groundY:69,sx:1.55,sy:1.48,sz:1.34,thickness:1.45,profile:{sizeClass:'XL',silhouette:'very broad barrel body, short neck, massive head'},jointTweaks:{neck:V(.18,0,.10),head:V(.34,0,.03),tailBase:V(-.20,0,.03),tailTip:V(-.18,0,-.05)},plateTweaks:{castShadow:[2.15,1.36],torsoPlate:[.92],pelvisPlate:[.90,.78],neckPlate:[.48],headConnectorPlate:[.48],headPlate:[.68,.70],tailPlate:[.11]}});
tuneQuadrupedLimbs(rhino,.25,.22,[.31,.24]);
addMuzzle(rhino,{length:.34,width:.48,height:.52,id:'snout'});
rhino.joints.push(joint('nasalHornBase','snout',V(.12,0,.12),{role:'horn'}),joint('nasalHornTip','nasalHornBase',V(.34,0,.10),{role:'horn'}));
rhino.plates.push(taperedSpanPlate('nasalHornPlate','nasalHornBase','nasalHornTip',.18,'accent',6));
rhino.anchors.push({id:'nasalHornTipAnchor',bone:'nasalHornTip',offset:V(.03,0,0),inheritScale:false});
rhino.clips.attack.frames[1].poses.nasalHornTip=V(.16,0,.04);
Object.assign(rhino.plates.find(p=>p.id==='nasalHornPlate'),{role:'horn',occlusionMode:'surface-relative',occlusionReference:'snout'});
const elephant=quadrupedVariant({id:'elephantBase',archetypes:['elephant','mammoth-like megafauna'],height:3.15,scale:14,groundY:72,sx:1.62,sy:1.60,sz:2.10,thickness:1.70,profile:{sizeClass:'XL',silhouette:'huge wide body, broad head, trunk and paired tusks'},jointTweaks:{neck:V(.16,0,.08),head:V(.30,0,-.02),tailBase:V(-.30,0,.05),tailTip:V(-.40,0,-.20)},plateTweaks:{castShadow:[2.45,1.55],torsoPlate:[1.15],pelvisPlate:[1.12,.98],neckPlate:[.60],headConnectorPlate:[.62],headPlate:[.94,.88],tailPlate:[.12]}});
tuneQuadrupedLimbs(elephant,.31,.27,[.36,.29]);
elephant.joints.push(joint('trunkBase','head',V(.25,0,-.10),{role:'snout'}),joint('trunkMid','trunkBase',V(.34,0,-.18),{role:'trunk',bendAxis:V(0,1,0),limits:[-70,80]}),joint('trunkTip','trunkMid',V(.32,0,-.16),{role:'trunk',ik:'trunkChain'}),joint('nearTuskBase','head',V(.16,.20,-.07),{role:'tusk',mirror:'farTuskBase'}),joint('nearTuskTip','nearTuskBase',V(.45,.03,-.10),{role:'tusk',mirror:'farTuskTip'}),joint('farTuskBase','head',V(.16,-.20,-.07),{role:'tusk',mirror:'nearTuskBase'}),joint('farTuskTip','farTuskBase',V(.45,-.03,-.10),{role:'tusk',mirror:'nearTuskTip'}));
elephant.plates.push(spanPlate('trunkConnectorPlate','head','trunkBase',.42,'body',5.3),spanPlate('trunkUpperPlate','trunkBase','trunkMid',.28,'body',5.4),spanPlate('trunkLowerPlate','trunkMid','trunkTip',.20,'accent',5.5),plate('trunkTipPlate','trunkTip','ellipse',[.23,.20],'accent',5.6),taperedSpanPlate('nearTuskPlate','nearTuskBase','nearTuskTip',.15,'accent',6),taperedSpanPlate('farTuskPlate','farTuskBase','farTuskTip',.15,'accent',6));
elephant.anchors.push({id:'trunkTipAnchor',bone:'trunkTip',offset:V(.05,0,0),inheritScale:false},{id:'nearTuskTipAnchor',bone:'nearTuskTip',offset:V(.03,0,0),counterpart:'farTuskTipAnchor',inheritScale:false},{id:'farTuskTipAnchor',bone:'farTuskTip',offset:V(.03,0,0),counterpart:'nearTuskTipAnchor',inheritScale:false});
elephant.clips.idleA.frames[1].poses.trunkTip=V(-.03,.04,.03);
elephant.clips.walkA.frames[0].poses.trunkTip=V(0,.08,.02);
elephant.clips.walkA.frames[1].poses.trunkTip=V(0,-.08,.02);
elephant.clips.walkA.frames[2].poses.trunkTip=V(0,.08,.02);
elephant.clips.attack.frames[1].poses.trunkMid=V(.18,0,.08);
elephant.clips.attack.frames[1].poses.trunkTip=V(.30,0,.12);
const rabbit=quadrupedVariant({id:'rabbitBase',archetypes:['rabbit','hare'],height:.28,scale:48,groundY:72,sx:.50,sy:.60,sz:.38,thickness:.68,profile:{sizeClass:'XS',silhouette:'compact body, powerful haunches, paired floppy ears'},jointTweaks:{neck:V(.10,0,.05),head:V(.16,0,.02),tailBase:V(-.13,0,.04),tailTip:V(-.09,0,.04),nearRearHip:V(-.02,.15,-.01),farRearHip:V(-.02,-.15,-.01)},plateTweaks:{castShadow:[.72,.48],torsoPlate:[.34],pelvisPlate:[.48,.46],neckPlate:[.20],headConnectorPlate:[.21],headPlate:[.36,.38],tailPlate:[.18]}});
tuneQuadrupedLimbs(rabbit,.10,.08,[.15,.11]);
for(const p of rabbit.plates){if(p.id.includes('Rear')&&p.id.endsWith('UpperPlate'))p.size=[.16];if(p.id.includes('Rear')&&p.id.endsWith('PawPlate'))p.size=[.22,.15]}addPairedEars(rabbit,{baseX:-.02,baseY:.09,baseZ:.06,tipX:-.15,tipY:.22,tipZ:-.05,width:.12,style:'flat-floppy'});
rabbit.clips.walkA.events=[{t:0,name:'hop-compress'},{t:.5,name:'hop-land'}];
const leopard=quadrupedVariant({id:'leopardBase',archetypes:['leopard','panther','big cat'],height:.76,scale:31,groundY:70,sx:1.24,sy:.88,sz:.84,thickness:.84,profile:{sizeClass:'medium',silhouette:'low long feline torso, rounded head, broad paws, long flexible tail'},jointTweaks:{neck:V(.18,0,.08),head:V(.24,0,.02),tailBase:V(-.34,0,.03),tailTip:V(-.55,0,-.08)},plateTweaks:{castShadow:[1.20,1.10],torsoPlate:[.48],pelvisPlate:[.55,.58],neckPlate:[.25],headConnectorPlate:[.25],headPlate:[.43,.44],tailPlate:[.15]}});
tuneQuadrupedLimbs(leopard,.14,.12,[.24,.18]);
addMuzzle(leopard,{length:.15,width:.24,height:.25,id:'muzzle'});
addPairedEars(leopard,{baseX:-.03,baseY:.10,baseZ:.08,tipX:-.06,tipY:.06,tipZ:.05,width:.13,style:'rounded-feline'});
leopard.clips.idleA.frames[1].poses.tailTip=V(0,.09,.02);
const wolf=quadrupedVariant({id:'wolfBase',archetypes:['wolf','dire wolf'],height:.90,scale:29,groundY:70,sx:1.14,sy:.82,sz:1.04,thickness:.92,profile:{sizeClass:'medium',silhouette:'deep chest, tapered waist, long muzzle, pointed ears, brush tail'},jointTweaks:{neck:V(.27,0,.15),head:V(.29,0,.04),tailBase:V(-.31,0,.08),tailTip:V(-.43,0,-.04)},plateTweaks:{castShadow:[1.15,.92],torsoPlate:[.56],pelvisPlate:[.47,.48],neckPlate:[.31],headConnectorPlate:[.29],headPlate:[.40,.43],tailPlate:[.19]}});
tuneQuadrupedLimbs(wolf,.16,.13,[.20,.15]);
addMuzzle(wolf,{length:.25,width:.22,height:.27,id:'muzzle'});
addPairedEars(wolf,{baseX:-.03,baseY:.10,baseZ:.09,tipX:-.08,tipY:.08,tipZ:.14,width:.11,style:'pointed-canine'});
const greyhound=quadrupedVariant({id:'greyhoundBase',archetypes:['greyhound','sighthound'],height:.82,scale:30,groundY:72,sx:1.34,sy:.56,sz:1.12,thickness:.60,profile:{sizeClass:'medium',silhouette:'very narrow waist, deep chest, long legs, long neck and snout'},jointTweaks:{neck:V(.33,0,.17),head:V(.30,0,.03),tailBase:V(-.32,0,.03),tailTip:V(-.52,0,-.13)},plateTweaks:{castShadow:[.78,1.20],torsoPlate:[.34],pelvisPlate:[.31,.38],neckPlate:[.20],headConnectorPlate:[.20],headPlate:[.26,.34],tailPlate:[.08]}});
tuneQuadrupedLimbs(greyhound,.10,.08,[.15,.10]);
addMuzzle(greyhound,{length:.29,width:.15,height:.22,id:'muzzle'});
addPairedEars(greyhound,{baseX:-.03,baseY:.07,baseZ:.07,tipX:-.08,tipY:.07,tipZ:.05,width:.08,style:'folded-sighthound'});
const lizardJoints=[joint('root',null,V(0,0,0),{role:'root'}),joint('pelvis','root',V(-.28,0,.24),{role:'body'}),joint('chest','pelvis',V(.58,0,.05),{role:'body'}),joint('neck','chest',V(.24,0,.02),{role:'neck'}),joint('head','neck',V(.28,0,.01),{role:'head'}),joint('tailBase','pelvis',V(-.26,0,-.01),{role:'tail'}),joint('tailMid','tailBase',V(-.42,0,-.03),{role:'tail'}),joint('tailTip','tailMid',V(-.42,0,-.04),{role:'tail'}),
  joint('nearFrontShoulder','chest',V(-.04,.18,-.02),{role:'limb',mirror:'farFrontShoulder'}),joint('nearFrontElbow','nearFrontShoulder',V(-.04,.28,-.10),{role:'limb',mirror:'farFrontElbow',bendAxis:V(0,0,1),limits:[0,145]}),joint('nearFrontFoot','nearFrontElbow',V(.12,.22,-.11),{role:'limb',mirror:'farFrontFoot',ik:'nearFrontLeg'}),joint('farFrontShoulder','chest',V(-.04,-.18,-.02),{role:'limb',mirror:'nearFrontShoulder'}),joint('farFrontElbow','farFrontShoulder',V(-.04,-.28,-.10),{role:'limb',mirror:'nearFrontElbow',bendAxis:V(0,0,-1),limits:[0,145]}),joint('farFrontFoot','farFrontElbow',V(.12,-.22,-.11),{role:'limb',mirror:'nearFrontFoot',ik:'farFrontLeg'}),
  joint('nearRearHip','pelvis',V(-.03,.18,-.01),{role:'limb',mirror:'farRearHip'}),joint('nearRearKnee','nearRearHip',V(-.08,.29,-.10),{role:'limb',mirror:'farRearKnee',bendAxis:V(0,0,1),limits:[0,145]}),joint('nearRearFoot','nearRearKnee',V(-.12,.21,-.11),{role:'limb',mirror:'farRearFoot',ik:'nearRearLeg'}),joint('farRearHip','pelvis',V(-.03,-.18,-.01),{role:'limb',mirror:'nearRearHip'}),joint('farRearKnee','farRearHip',V(-.08,-.29,-.10),{role:'limb',mirror:'nearRearKnee',bendAxis:V(0,0,-1),limits:[0,145]}),joint('farRearFoot','farRearKnee',V(-.12,-.21,-.11),{role:'limb',mirror:'nearRearFoot',ik:'farRearLeg'})];
const lizard=templateRig({id:'lizardBase',family:'quadrupedLizard',archetypes:['komodo','chameleon'],height:.42,scale:22,groundY:68,profile:{torso:'slender',tail:'long articulated',stance:'splayed'},joints:lizardJoints,
  plates:[plate('castShadow','root','ellipse',[1.48,.62],'shadow',-99),spanPlate('torsoPlate','pelvis','chest',.38,'body',3),plate('pelvisPlate','pelvis','ellipse',[.40,.36],'body',3.1),spanPlate('neckPlate','chest','neck',.25,'body',4),spanPlate('headConnectorPlate','neck','head',.27,'body',4.8),plate('headPlate','head','ellipse',[.34,.38],'accent',5),spanPlate('tailBasePlate','pelvis','tailBase',.24,'body',2.5),spanPlate('tailMidPlate','tailBase','tailMid',.17,'accent',2),spanPlate('tailTipPlate','tailMid','tailTip',.10,'accent',1.8),...['nearFront','farFront'].flatMap(n=>[spanPlate(n+'UpperPlate',n+'Shoulder',n+'Elbow',.12,'body',1),spanPlate(n+'LowerPlate',n+'Elbow',n+'Foot',.10,'body',1.2),plate(n+'FootPlate',n+'Foot','ellipse',[.17,.11],'accent',0)]),...['nearRear','farRear'].flatMap(n=>[spanPlate(n+'UpperPlate',n+'Hip',n+'Knee',.13,'body',1),spanPlate(n+'LowerPlate',n+'Knee',n+'Foot',.10,'body',1.2),plate(n+'FootPlate',n+'Foot','ellipse',[.17,.11],'accent',0)])],
  anchors:[{id:'headCrestAnchor',bone:'head',offset:V(0,0,.14),inheritScale:false},{id:'backAnchor',bone:'chest',offset:V(-.10,0,.18),inheritScale:false},{id:'tailTipAnchor',bone:'tailTip',offset:V(-.05,0,0),inheritScale:false}],
  clips:clipPack({idle:{tailTip:[0,.07,.01],head:[.01,0,.01]},moveA:{nearFrontFoot:[.12,-.04,.03],farRearFoot:[.10,.04,.03],farFrontFoot:[-.10,.03,0],nearRearFoot:[-.10,-.03,0],tailTip:[0,.10,0]},moveB:{nearFrontFoot:[-.10,-.03,0],farRearFoot:[-.10,.03,0],farFrontFoot:[.12,.04,.03],nearRearFoot:[.10,-.04,.03],tailTip:[0,-.10,0]},attack:{head:[.24,0,.02],neck:[.15,0,.01],tailTip:[0,-.16,.02]},contacts:['nearFrontFoot','farFrontFoot','nearRearFoot','farRearFoot'],intervals:[{ids:['farFrontFoot','nearRearFoot'],from:0,to:.48},{ids:['nearFrontFoot','farRearFoot'],from:.5,to:.98}]})});
const dragon=templateRig({id:'dragonBase',family:'dragon',archetypes:['western dragon','wyvern-like quadruped'],height:.82,scale:22,groundY:68,profile:{base:'quadruped lizard',wings:'paired armature plus six-point resizable membranes',tail:'long articulated'},
  joints:[...lizard.joints.map(j=>({...j,bind:[...j.bind]})),joint('nearWingRoot','chest',V(-.08,.20,.22),{role:'wing',mirror:'farWingRoot'}),joint('nearWingElbow','nearWingRoot',V(-.10,.26,.02),{role:'wing',mirror:'farWingElbow',bendAxis:V(1,0,0),limits:[-25,120]}),joint('nearWingTip','nearWingElbow',V(-.14,.24,-.05),{role:'wing',mirror:'farWingTip'}),joint('nearWingTrailingRoot','chest',V(-.30,.17,.10),{role:'wingMembrane',mirror:'farWingTrailingRoot'}),joint('nearWingTrailingMid','nearWingElbow',V(-.28,-.12,-.08),{role:'wingMembrane',mirror:'farWingTrailingMid'}),joint('nearWingTrailingTip','nearWingTip',V(-.16,-.10,-.02),{role:'wingMembrane',mirror:'farWingTrailingTip'}),joint('farWingRoot','chest',V(-.08,-.20,.22),{role:'wing',mirror:'nearWingRoot'}),joint('farWingElbow','farWingRoot',V(-.10,-.26,.02),{role:'wing',mirror:'nearWingElbow',bendAxis:V(-1,0,0),limits:[-25,120]}),joint('farWingTip','farWingElbow',V(-.14,-.24,-.05),{role:'wing',mirror:'nearWingTip'}),joint('farWingTrailingRoot','chest',V(-.30,-.17,.10),{role:'wingMembrane',mirror:'nearWingTrailingRoot'}),joint('farWingTrailingMid','farWingElbow',V(-.28,.12,-.08),{role:'wingMembrane',mirror:'nearWingTrailingMid'}),joint('farWingTrailingTip','farWingTip',V(-.16,.10,-.02),{role:'wingMembrane',mirror:'nearWingTrailingTip'})],
  plates:[...lizard.plates.map(p=>p.id==='castShadow'?plate('castShadow','root','ellipse',[1.65,1.15],'shadow',-99):({...p,size:[...p.size],span:p.span?[...p.span]:undefined})),polygonPlate('nearWingMembrane','nearWingRoot',['nearWingRoot','nearWingElbow','nearWingTip','nearWingTrailingTip','nearWingTrailingMid','nearWingTrailingRoot'],'accent',3.7),polygonPlate('farWingMembrane','farWingRoot',['farWingRoot','farWingTrailingRoot','farWingTrailingMid','farWingTrailingTip','farWingTip','farWingElbow'],'accent',3.7),spanPlate('nearWingArmPlate','nearWingRoot','nearWingElbow',.18,'accent',4.2),spanPlate('nearWingForePlate','nearWingElbow','nearWingTip',.15,'accent',4.1),plate('nearWingTipPlate','nearWingTip','ellipse',[.16,.20],'accent',4),spanPlate('farWingArmPlate','farWingRoot','farWingElbow',.18,'accent',4.2),spanPlate('farWingForePlate','farWingElbow','farWingTip',.15,'accent',4.1),plate('farWingTipPlate','farWingTip','ellipse',[.16,.20],'accent',4)],
  anchors:[{id:'hornAnchor',bone:'head',offset:V(-.03,0,.18),inheritScale:false},{id:'riderAnchor',bone:'chest',offset:V(-.10,0,.30),inheritScale:false},{id:'nearWingTipAnchor',bone:'nearWingTip',offset:V(0,.05,0),inheritScale:false},{id:'farWingTipAnchor',bone:'farWingTip',offset:V(0,-.05,0),inheritScale:false},{id:'nearWingMembraneAnchor',bone:'nearWingTrailingMid',offset:V(0,0,0),inheritScale:false},{id:'farWingMembraneAnchor',bone:'farWingTrailingMid',offset:V(0,0,0),inheritScale:false}],
  clips:clipPack({idle:{nearWingTip:[0,-.03,.03],farWingTip:[0,.03,.03],nearWingTrailingTip:[0,-.02,.02],farWingTrailingTip:[0,.02,.02],tailTip:[0,.06,0]},moveA:{nearWingElbow:[0,.18,.10],nearWingTip:[0,.34,.14],nearWingTrailingMid:[0,.10,.06],nearWingTrailingTip:[0,.26,.10],farWingElbow:[0,-.18,.10],farWingTip:[0,-.34,.14],farWingTrailingMid:[0,-.10,.06],farWingTrailingTip:[0,-.26,.10]},moveB:{nearWingElbow:[0,-.08,-.06],nearWingTip:[0,-.14,-.08],nearWingTrailingMid:[0,-.05,-.04],nearWingTrailingTip:[0,-.10,-.06],farWingElbow:[0,.08,-.06],farWingTip:[0,.14,-.08],farWingTrailingMid:[0,.05,-.04],farWingTrailingTip:[0,.10,-.06]},attack:{head:[.28,0,.04],neck:[.16,0,.02],nearWingTip:[0,.30,.12],nearWingTrailingTip:[0,.22,.08],farWingTip:[0,-.30,.12],farWingTrailingTip:[0,-.22,.08]},contacts:['nearFrontFoot','farFrontFoot','nearRearFoot','farRearFoot'],intervals:[{ids:['nearFrontFoot','farFrontFoot','nearRearFoot','farRearFoot'],from:0,to:1}],moveEventA:'wings-spread',moveEventB:'wings-fold'})});
const walkingBird=templateRig({id:'walkingBirdBase',family:'theropodAvianWalking',archetypes:['chicken','chocobo','giant walking owl'],height:.92,scale:32,groundY:74,profile:{stance:'biped digitigrade',wings:'folded',tail:'counterbalance'},
  joints:[joint('root',null,V(0,0,0),{role:'root'}),joint('pelvis','root',V(-.12,0,.55),{role:'body'}),joint('chest','pelvis',V(.22,0,.12),{role:'body'}),joint('neck','chest',V(.24,0,.16),{role:'neck'}),joint('head','neck',V(.18,0,.07),{role:'head'}),joint('beak','head',V(.16,0,-.03),{role:'head'}),joint('tailBase','pelvis',V(-.24,0,.02),{role:'tail'}),joint('tailTip','tailBase',V(-.34,0,-.08),{role:'tail'}),joint('nearHip','pelvis',V(0,.12,-.02),{role:'limb',mirror:'farHip'}),joint('nearKnee','nearHip',V(.07,0,-.28),{role:'limb',mirror:'farKnee',bendAxis:V(0,1,0),limits:[0,150]}),joint('nearFoot','nearKnee',V(-.03,0,-.27),{role:'limb',mirror:'farFoot'}),joint('nearToe','nearFoot',V(.17,0,0),{role:'limb',mirror:'farToe',ik:'nearLeg'}),joint('farHip','pelvis',V(0,-.12,-.02),{role:'limb',mirror:'nearHip'}),joint('farKnee','farHip',V(.07,0,-.28),{role:'limb',mirror:'nearKnee',bendAxis:V(0,1,0),limits:[0,150]}),joint('farFoot','farKnee',V(-.03,0,-.27),{role:'limb',mirror:'nearFoot'}),joint('farToe','farFoot',V(.17,0,0),{role:'limb',mirror:'nearToe',ik:'farLeg'}),joint('nearWing','chest',V(-.02,.20,.02),{role:'wing',mirror:'farWing'}),joint('nearWingTip','nearWing',V(-.16,.15,-.04),{role:'wing',mirror:'farWingTip'}),joint('farWing','chest',V(-.02,-.20,.02),{role:'wing',mirror:'nearWing'}),joint('farWingTip','farWing',V(-.16,-.15,-.04),{role:'wing',mirror:'nearWingTip'})],
  plates:[plate('castShadow','root','ellipse',[.78,.52],'shadow',-99),spanPlate('bodyPlate','pelvis','chest',.52,'body',3),plate('pelvisPlate','pelvis','ellipse',[.52,.46],'body',3.1),spanPlate('neckPlate','chest','neck',.20,'body',4),spanPlate('headConnectorPlate','neck','head',.24,'body',4.8),plate('headPlate','head','ellipse',[.32,.36],'body',5),spanPlate('beakPlate','head','beak',.15,'accent',5.2),spanPlate('tailPlate','tailBase','tailTip',.18,'accent',2),...['near','far'].flatMap(n=>[spanPlate(n+'ThighPlate',n+'Hip',n+'Knee',.15,'body',1),spanPlate(n+'ShinPlate',n+'Knee',n+'Foot',.11,'body',1.1),spanPlate(n+'ToePlate',n+'Foot',n+'Toe',.07,'accent',0)]),spanPlate('nearWingPlate','nearWing','nearWingTip',.22,'accent',3.8),spanPlate('farWingPlate','farWing','farWingTip',.22,'accent',3.8)],
  anchors:[{id:'headgearAnchor',bone:'head',offset:V(0,0,.15),inheritScale:false},{id:'saddleAnchor',bone:'chest',offset:V(-.08,0,.24),inheritScale:false},{id:'beakTipAnchor',bone:'beak',offset:V(.05,0,0),inheritScale:false}],
  clips:clipPack({idle:{head:[0,0,.02],tailTip:[0,.03,0]},moveA:{nearFoot:[.16,0,.07],nearToe:[.08,0,.05],farFoot:[-.12,0,0],nearWingTip:[-.02,-.03,.02]},moveB:{nearFoot:[-.12,0,0],farFoot:[.16,0,.07],farToe:[.08,0,.05],farWingTip:[-.02,.03,.02]},attack:{beak:[.22,0,.02],head:[.12,0,.02],neck:[.10,0,.01]},contacts:['nearToe','farToe'],intervals:[{ids:['farToe'],from:0,to:.48},{ids:['nearToe'],from:.5,to:.98}],moveEventA:'near-step',moveEventB:'far-step'})});
const flyingBird=templateRig({id:'flyingBirdBase',family:'theropodAvianFlying',archetypes:['eagle','phoenix'],height:1.08,scale:27,groundY:77,profile:{stance:'airborne',wings:'three-segment spread',feet:'tucked'},
  joints:[joint('root',null,V(0,0,0),{role:'root'}),joint('body','root',V(-.08,0,.82),{role:'body'}),joint('chest','body',V(.24,0,.06),{role:'body'}),joint('neck','chest',V(.22,0,.08),{role:'neck'}),joint('head','neck',V(.17,0,.05),{role:'head'}),joint('beak','head',V(.15,0,-.02),{role:'head'}),joint('tailBase','body',V(-.28,0,-.03),{role:'tail'}),joint('tailTip','tailBase',V(-.38,0,-.08),{role:'tail'}),joint('nearWingRoot','chest',V(-.04,.18,.02),{role:'wing',mirror:'farWingRoot'}),joint('nearWingElbow','nearWingRoot',V(-.08,.38,.02),{role:'wing',mirror:'farWingElbow'}),joint('nearWingWrist','nearWingElbow',V(-.15,.40,-.04),{role:'wing',mirror:'farWingWrist'}),joint('nearWingTip','nearWingWrist',V(-.18,.34,-.06),{role:'wing',mirror:'farWingTip'}),joint('farWingRoot','chest',V(-.04,-.18,.02),{role:'wing',mirror:'nearWingRoot'}),joint('farWingElbow','farWingRoot',V(-.08,-.38,.02),{role:'wing',mirror:'nearWingElbow'}),joint('farWingWrist','farWingElbow',V(-.15,-.40,-.04),{role:'wing',mirror:'nearWingWrist'}),joint('farWingTip','farWingWrist',V(-.18,-.34,-.06),{role:'wing',mirror:'nearWingTip'}),joint('nearTalon','body',V(.04,.11,-.18),{role:'limb',mirror:'farTalon'}),joint('farTalon','body',V(.04,-.11,-.18),{role:'limb',mirror:'nearTalon'})],
  plates:[plate('castShadow','root','ellipse',[1.05,.64],'shadow',-99),spanPlate('bodyPlate','body','chest',.48,'body',3),spanPlate('neckPlate','chest','neck',.20,'body',4),spanPlate('headConnectorPlate','neck','head',.23,'body',4.8),plate('headPlate','head','ellipse',[.30,.34],'body',5),spanPlate('beakPlate','head','beak',.14,'accent',5.2),spanPlate('tailConnectorPlate','body','tailBase',.30,'body',2.5),spanPlate('tailPlate','tailBase','tailTip',.24,'accent',2),...['near','far'].flatMap(n=>[spanPlate(n+'WingUpperPlate',n+'WingRoot',n+'WingElbow',.28,'accent',4),spanPlate(n+'WingMidPlate',n+'WingElbow',n+'WingWrist',.34,'accent',4.1),spanPlate(n+'WingTipPlate',n+'WingWrist',n+'WingTip',.24,'accent',4)]),plate('nearTalonPlate','nearTalon','ellipse',[.13,.11],'accent',2.5),plate('farTalonPlate','farTalon','ellipse',[.13,.11],'accent',2.5)],
  anchors:[{id:'headCrestAnchor',bone:'head',offset:V(-.02,0,.16),inheritScale:false},{id:'backAnchor',bone:'chest',offset:V(-.10,0,.20),inheritScale:false},{id:'nearTalonGripAnchor',bone:'nearTalon',offset:V(.03,0,0),inheritScale:false},{id:'farTalonGripAnchor',bone:'farTalon',offset:V(.03,0,0),inheritScale:false}],
  clips:clipPack({idle:{nearWingTip:[0,.04,.03],farWingTip:[0,-.04,.03],body:[0,0,.02]},moveA:{nearWingElbow:[0,-.10,.14],nearWingWrist:[0,-.16,.18],nearWingTip:[0,-.18,.20],farWingElbow:[0,.10,-.08],farWingWrist:[0,.16,-.10],farWingTip:[0,.18,-.12]},moveB:{nearWingElbow:[0,.10,-.08],nearWingWrist:[0,.16,-.10],nearWingTip:[0,.18,-.12],farWingElbow:[0,-.10,.14],farWingWrist:[0,-.16,.18],farWingTip:[0,-.18,.20]},attack:{beak:[.24,0,.02],head:[.12,0,.02],nearTalon:[.18,.03,-.12],farTalon:[.18,-.03,-.12]},contacts:[],intervals:[],moveDuration:760,moveEventA:'near-wing-down',moveEventB:'far-wing-down'})});
const bugLegData=[['nearFrontFoot',V(.28,.42,-.08),'farFrontFoot'],['farFrontFoot',V(.28,-.42,-.08),'nearFrontFoot'],['nearMiddleFoot',V(0,.46,-.08),'farMiddleFoot'],['farMiddleFoot',V(0,-.46,-.08),'nearMiddleFoot'],['nearRearFoot',V(-.30,.40,-.08),'farRearFoot'],['farRearFoot',V(-.30,-.40,-.08),'nearRearFoot']];
const bug=templateRig({id:'bugBase',family:'bugContinuous',archetypes:['cockroach','beetle-like crawler'],height:.20,scale:39,groundY:68,profile:{body:'continuous shell',legs:'six unsegmented'},
  joints:[joint('root',null,V(0,0,0),{role:'root'}),joint('body','root',V(0,0,.10),{role:'body'}),...bugLegData.map(([id,v,mirror])=>joint(id,'body',v,{role:'limb',mirror,ik:id.replace('Foot','Leg')}))],
  plates:[plate('castShadow','root','ellipse',[1.12,.72],'shadow',-99),plate('shellPlate','body','ellipse',[.56,1.05],'body',3),...bugLegData.map(([id])=>spanPlate(id+'Plate','body',id,.075,'accent',1))],
  anchors:[{id:'shellTopAnchor',bone:'body',offset:V(0,0,.10),inheritScale:false}],
  clips:clipPack({idle:{body:[.01,0,.01]},moveA:{nearFrontFoot:[.10,-.04,.02],farMiddleFoot:[.08,.03,.02],nearRearFoot:[.08,-.03,.02]},moveB:{farFrontFoot:[.10,.04,.02],nearMiddleFoot:[.08,-.03,.02],farRearFoot:[.08,.03,.02]},attack:{body:[.18,0,.02],nearFrontFoot:[.12,-.08,.02],farFrontFoot:[.12,.08,.02]},contacts:bugLegData.map(x=>x[0]),intervals:[{ids:['farFrontFoot','nearMiddleFoot','farRearFoot'],from:0,to:.48},{ids:['nearFrontFoot','farMiddleFoot','nearRearFoot'],from:.5,to:.98}],moveDuration:620,moveEventA:'tripod-a',moveEventB:'tripod-b'})});
const antLegJoints=[],antLegPlates=[],antFeet=[];
for(const [side,sgn] of [['near',1],['far',-1]])for(const [part,x] of [['Front',.20],['Middle',0],['Rear',-.20]]){const knee=`${side}${part}Knee`,foot=`${side}${part}Foot`,mirror=`${side==='near'?'far':'near'}${part}`;antLegJoints.push(joint(knee,'thorax',V(x,.28*sgn,-.05),{role:'limb',mirror:mirror+'Knee'}),joint(foot,knee,V(x*.35,.28*sgn,-.08),{role:'limb',mirror:mirror+'Foot',ik:`${side}${part}Leg`}));antLegPlates.push(spanPlate(knee+'Plate','thorax',knee,.065,'body',1),spanPlate(foot+'Plate',knee,foot,.05,'accent',1.1));antFeet.push(foot)}
const ant=templateRig({id:'antBase',family:'bugSegmented',archetypes:['ant','segmented arthropod'],height:.25,scale:37,groundY:68,profile:{body:'head thorax abdomen',legs:'six two-segment',antennae:'paired'},
  joints:[joint('root',null,V(0,0,0),{role:'root'}),joint('thorax','root',V(0,0,.13),{role:'body'}),joint('head','thorax',V(.40,0,.01),{role:'head'}),joint('mandible','head',V(.20,0,-.02),{role:'head'}),joint('abdomen','thorax',V(-.44,0,.01),{role:'body'}),...antLegJoints,joint('nearAntennaBase','head',V(.08,.08,.02),{role:'antenna',mirror:'farAntennaBase'}),joint('nearAntennaTip','nearAntennaBase',V(.18,.13,.01),{role:'antenna',mirror:'farAntennaTip'}),joint('farAntennaBase','head',V(.08,-.08,.02),{role:'antenna',mirror:'nearAntennaBase'}),joint('farAntennaTip','farAntennaBase',V(.18,-.13,.01),{role:'antenna',mirror:'nearAntennaTip'})],
  plates:[plate('castShadow','root','ellipse',[1.35,.64],'shadow',-99),plate('thoraxPlate','thorax','ellipse',[.36,.42],'body',3),plate('headPlate','head','ellipse',[.34,.38],'accent',3.2),spanPlate('mandiblePlate','head','mandible',.16,'accent',3.3),plate('abdomenPlate','abdomen','ellipse',[.46,.55],'body',3),...antLegPlates,spanPlate('nearAntennaPlate','nearAntennaBase','nearAntennaTip',.035,'accent',2.5),spanPlate('farAntennaPlate','farAntennaBase','farAntennaTip',.035,'accent',2.5)],
  anchors:[{id:'mandibleAnchor',bone:'mandible',offset:V(.04,0,0),inheritScale:false},{id:'abdomenTopAnchor',bone:'abdomen',offset:V(0,0,.10),inheritScale:false}],
  clips:clipPack({idle:{nearAntennaTip:[0,.03,.01],farAntennaTip:[0,-.03,.01]},moveA:{nearFrontFoot:[.08,-.03,.02],farMiddleFoot:[.07,.03,.02],nearRearFoot:[.07,-.03,.02]},moveB:{farFrontFoot:[.08,.03,.02],nearMiddleFoot:[.07,-.03,.02],farRearFoot:[.07,.03,.02]},attack:{mandible:[.18,0,.01],nearAntennaTip:[.08,-.04,.02],farAntennaTip:[.08,.04,.02]},contacts:antFeet,intervals:[{ids:['farFrontFoot','nearMiddleFoot','farRearFoot'],from:0,to:.48},{ids:['nearFrontFoot','farMiddleFoot','nearRearFoot'],from:.5,to:.98}],moveDuration:640,moveEventA:'tripod-a',moveEventB:'tripod-b'})});
const radialJoints=[joint('root',null,V(0,0,0),{role:'root'}),joint('core','root',V(0,0,.16),{role:'body'})],radialPlates=[plate('castShadow','root','ellipse',[1.35,1.35],'shadow',-99),plate('corePlate','core','ellipse',[.48,.48],'body',3)],radialContacts=[],radialMoveA={},radialMoveB={};
for(let i=0;i<8;i++){const a=i*Math.PI/4,c=Math.cos(a),s=Math.sin(a),base=`tentacle${i}Base`,mid=`tentacle${i}Mid`,tip=`tentacle${i}Tip`;radialJoints.push(joint(base,'core',V(.16*c,.16*s,-.02),{role:'tentacle',radialIndex:i}),joint(mid,base,V(.28*c,.28*s,-.04),{role:'tentacle',radialIndex:i}),joint(tip,mid,V(.25*c,.25*s,-.05),{role:'tentacle',radialIndex:i,ik:`tentacle${i}Chain`}));radialPlates.push(spanPlate(`tentacle${i}UpperPlate`,base,mid,.12,'body',2),spanPlate(`tentacle${i}LowerPlate`,mid,tip,.085,'accent',1.8),plate(`tentacle${i}TipPlate`,tip,'ellipse',[.12,.10],'accent',1.7));radialContacts.push(tip);const sway=.07*(i%2?1:-1);radialMoveA[tip]=V(-s*sway,c*sway,.02);radialMoveB[tip]=V(s*sway,-c*sway,.02)}
const radial=templateRig({id:'radialBase',family:'radialTentacled',archetypes:['seastar','anemone','penomena','squid','jellyfish','octopus'],height:.34,scale:39,groundY:68,profile:{core:'single radial hub',appendages:8,segmentsPerAppendage:2},joints:radialJoints,plates:radialPlates,
  anchors:[{id:'coreTopAnchor',bone:'core',offset:V(0,0,.14),inheritScale:false},{id:'primaryTentacleAnchor',bone:'tentacle0Tip',offset:V(.04,0,0),inheritScale:false}],
  clips:clipPack({idle:{core:[0,0,.03],tentacle0Tip:[.03,0,.01],tentacle4Tip:[-.03,0,.01]},moveA:radialMoveA,moveB:radialMoveB,attack:{tentacle0Mid:[.16,0,.03],tentacle0Tip:[.30,0,.05]},contacts:radialContacts,intervals:[{ids:radialContacts,from:0,to:1}],moveDuration:1100,moveEventA:'radial-wave-a',moveEventB:'radial-wave-b'})});
const serpentine=templateRig({id:'serpentineBase',family:'serpentine',archetypes:['snake','worm','eel-like crawler'],height:.22,scale:36,groundY:68,profile:{spine:'seven-segment chain',limbs:0,locomotion:'lateral wave'},
  joints:[joint('root',null,V(0,0,0),{role:'root'}),joint('tailBase','root',V(-.72,0,.10),{role:'tail'}),joint('tailMid','tailBase',V(.28,.08,.01),{role:'tail'}),joint('rearSpine','tailMid',V(.30,-.14,.01),{role:'body'}),joint('middleSpine','rearSpine',V(.32,.14,.01),{role:'body'}),joint('frontSpine','middleSpine',V(.32,-.12,.01),{role:'body'}),joint('neck','frontSpine',V(.28,.08,.02),{role:'neck'}),joint('head','neck',V(.28,0,.04),{role:'head'}),joint('snout','head',V(.18,0,-.01),{role:'head'})],
  plates:[plate('castShadow','root','ellipse',[1.62,.54],'shadow',-99),spanPlate('tailBasePlate','tailBase','tailMid',.10,'accent',1),spanPlate('tailMidPlate','tailMid','rearSpine',.14,'body',2),spanPlate('rearBodyPlate','rearSpine','middleSpine',.19,'body',3),spanPlate('middleBodyPlate','middleSpine','frontSpine',.22,'body',3.2),spanPlate('frontBodyPlate','frontSpine','neck',.20,'body',3.4),spanPlate('neckPlate','neck','head',.17,'body',4),spanPlate('headConnectorPlate','head','snout',.20,'body',4.8),plate('headPlate','head','ellipse',[.28,.34],'accent',5),plate('snoutPlate','snout','ellipse',[.20,.23],'accent',5.1)],
  anchors:[{id:'headgearAnchor',bone:'head',offset:V(0,0,.14),inheritScale:false},{id:'tailTipAnchor',bone:'tailBase',offset:V(-.05,0,0),inheritScale:false}],
  clips:clipPack({idle:{middleSpine:[0,.03,.01],head:[0,-.02,.01]},moveA:{tailMid:[0,-.10,.01],rearSpine:[0,.14,.01],middleSpine:[0,-.14,.01],frontSpine:[0,.12,.01],neck:[0,-.08,.01]},moveB:{tailMid:[0,.10,.01],rearSpine:[0,-.14,.01],middleSpine:[0,.14,.01],frontSpine:[0,-.12,.01],neck:[0,.08,.01]},attack:{neck:[.16,0,.03],head:[.28,0,.04],snout:[.12,0,.02]},contacts:['tailBase','tailMid','rearSpine','middleSpine','frontSpine'],intervals:[{ids:['tailBase','tailMid','rearSpine','middleSpine','frontSpine'],from:0,to:1}],moveDuration:900,moveEventA:'wave-a',moveEventB:'wave-b'})});
function articulatedLegSet({parent,pairs=4,xPositions,lateral=.18,reach=.30,upperWidth=.08,lowerWidth=.065,prefix='leg'}){const joints=[],plates=[],contacts=[],moveA={},moveB={},phaseA=[],phaseB=[];for(const[side,sgn]of[['left',1],['right',-1]])for(let i=0;i<pairs;i++){const n=i+1,x=xPositions?.[i]??(.30-i*.20),hip=`${side}${prefix}${n}Hip`,knee=`${side}${prefix}${n}Knee`,foot=`${side}${prefix}${n}Foot`,other=side==='left'?'right':'left',mirrorHip=`${other}${prefix}${n}Hip`,mirrorKnee=`${other}${prefix}${n}Knee`,mirrorFoot=`${other}${prefix}${n}Foot`;joints.push(joint(hip,parent,V(x,lateral*sgn,-.02),{role:'limb',mirror:mirrorHip}),joint(knee,hip,V(x*.18,reach*sgn,-.07),{role:'limb',mirror:mirrorKnee,bendAxis:V(1,0,0),limits:[-35,135]}),joint(foot,knee,V(-x*.10,reach*.45*sgn,-.09),{role:'limb',mirror:mirrorFoot,ik:`${side}${prefix}${n}Chain`}));plates.push(spanPlate(`${side}${prefix}${n}UpperPlate`,hip,knee,upperWidth,'body',1),spanPlate(`${side}${prefix}${n}LowerPlate`,knee,foot,lowerWidth,'accent',1.1),plate(`${side}${prefix}${n}FootPlate`,foot,'ellipse',[lowerWidth*1.45,lowerWidth*1.15],'accent',0));contacts.push(foot);const lift=(i+(side==='right'?1:0))%2===0;(lift?phaseA:phaseB).push(foot);moveA[foot]=lift?V(.09,0,.03):V(-.06,0,0);moveB[foot]=lift?V(-.06,0,0):V(.09,0,.03)}return{joints,plates,contacts,moveA,moveB,intervals:[{ids:phaseB,from:0,to:.48},{ids:phaseA,from:.5,to:.98}]}}
const mimic=templateRig({id:'mimicBase',family:'constructMimic',archetypes:['treasure-chest mimic','animated coffer'],height:.82,scale:34,groundY:72,profile:{silhouette:'rectangular treasure chest',mechanism:'single rear hinge with snapping lid',locomotion:'wobble'},
  joints:[joint('root',null,V(0,0,0),{role:'root'}),joint('chestBase','root',V(0,0,.28),{role:'body'}),joint('rearHinge','chestBase',V(-.38,0,.22),{role:'hinge',bendAxis:V(0,1,0),limits:[-82,8]}),joint('lidFront','rearHinge',V(.76,0,.02),{role:'body'}),joint('frontLock','chestBase',V(.39,0,.08),{role:'accessoryAnchor'}),joint('leftFoot','chestBase',V(-.18,.24,-.28),{role:'limb',mirror:'rightFoot'}),joint('rightFoot','chestBase',V(-.18,-.24,-.28),{role:'limb',mirror:'leftFoot'})],
  plates:[plate('castShadow','root','ellipse',[1.16,.82],'shadow',-99),pathPlate('chestBasePlate','chestBase','M -1 -.68 L 1 -.68 L 1 .68 L -1 .68 Z',[.98,.72],'body',3),pathPlate('mouthInteriorPlate','chestBase','M -.82 -.52 L .82 -.52 L .82 .52 L -.82 .52 Z',[.92,.64],'accent',3.4),spanPlate('lidPlate','rearHinge','lidFront',.72,'body',4.5),spanPlate('lidBandPlate','rearHinge','lidFront',.18,'accent',4.8),plate('frontLockPlate','frontLock','ellipse',[.18,.22],'accent',5),plate('leftFootPlate','leftFoot','ellipse',[.24,.17],'accent',0),plate('rightFootPlate','rightFoot','ellipse',[.24,.17],'accent',0)],
  anchors:[{id:'lockAccessoryAnchor',bone:'frontLock',offset:V(.04,0,0),inheritScale:false},{id:'lidTopAnchor',bone:'lidFront',offset:V(-.18,0,.12),inheritScale:false},{id:'chestCarryAnchor',bone:'chestBase',offset:V(0,0,.22),inheritScale:false}],
  clips:{idleA:{base:'bind',duration:1700,easing:'ease-in-out',loop:true,frames:[{t:0,poses:{},rotations:{rearHinge:V(0,0,0)}},{t:.5,poses:{chestBase:V(0,0,.02)},rotations:{rearHinge:V(0,-4,0)}},{t:1,poses:{},rotations:{rearHinge:V(0,0,0)}}],contacts:['leftFoot','rightFoot']},walkA:{base:'idleA',duration:820,easing:'ease-in-out',loop:true,frames:[{t:0,poses:{leftFoot:V(.10,0,.03),rightFoot:V(-.06,0,0)},rotations:{rearHinge:V(0,-5,4)}},{t:.5,poses:{leftFoot:V(-.06,0,0),rightFoot:V(.10,0,.03)},rotations:{rearHinge:V(0,-5,-4)}},{t:1,poses:{leftFoot:V(.10,0,.03),rightFoot:V(-.06,0,0)},rotations:{rearHinge:V(0,-5,4)}}],contactIntervals:[{ids:['rightFoot'],from:0,to:.48},{ids:['leftFoot'],from:.5,to:.98}],events:[{t:0,name:'left-step'},{t:.5,name:'right-step'}]},attack:{base:'idleA',duration:720,easing:'cubic-bezier(.2,.8,.2,1)',loop:false,frames:[{t:0,poses:{},rotations:{rearHinge:V(0,0,0)}},{t:.45,poses:{lidFront:V(.04,0,.06)},rotations:{rearHinge:V(0,-76,0)}},{t:.62,poses:{chestBase:V(.10,0,.03)},rotations:{rearHinge:V(0,-12,0)}},{t:1,poses:{},rotations:{rearHinge:V(0,0,0)}}],contacts:['leftFoot','rightFoot'],events:[{t:.45,name:'lid-open'},{t:.62,name:'impact'},{t:.84,name:'release'}]}}});
const tentacle=templateRig({id:'uprightTentacleBase',family:'uprightTentacle',archetypes:['striking tentacle','plant tendril','kraken arm'],height:1.48,scale:22,groundY:78,profile:{silhouette:'grounded column rising in +Z, curling forward, then hanging down',segments:4,attack:'forward lunge'},
  joints:[joint('root',null,V(0,0,0),{role:'root'}),joint('tentacleBase','root',V(0,0,.08),{role:'tentacle'}),joint('tentacleLower','tentacleBase',V(0,0,.52),{role:'tentacle',bendAxis:V(0,1,0),limits:[-55,55]}),joint('tentacleCrest','tentacleLower',V(.06,0,.48),{role:'tentacle',bendAxis:V(0,1,0),limits:[-70,70]}),joint('tentacleBend','tentacleCrest',V(.26,0,.20),{role:'tentacle',bendAxis:V(0,1,0),limits:[-95,95]}),joint('tentacleTip','tentacleBend',V(.30,0,-.42),{role:'tentacle',ik:'tentacleStrikeChain'})],
  plates:[plate('castShadow','root','ellipse',[.62,.48],'shadow',-99),plate('baseMassPlate','tentacleBase','ellipse',[.42,.36],'body',2),spanPlate('tentacleLowerPlate','tentacleBase','tentacleLower',.32,'body',2.5),spanPlate('tentacleCrestPlate','tentacleLower','tentacleCrest',.27,'body',3),spanPlate('tentacleBendPlate','tentacleCrest','tentacleBend',.22,'accent',3.4),taperedSpanPlate('tentacleHangingPlate','tentacleBend','tentacleTip',.18,'accent',3.6),plate('tentacleTipPlate','tentacleTip','ellipse',[.20,.17],'accent',3.8)],
  anchors:[{id:'tentacleTipAnchor',bone:'tentacleTip',offset:V(.06,0,0),inheritScale:false},{id:'tentacleBaseAccessoryAnchor',bone:'tentacleBase',offset:V(0,0,.10),inheritScale:false}],
  clips:clipPack({idle:{tentacleCrest:[0,.05,.02],tentacleBend:[-.02,.08,-.02],tentacleTip:[-.03,.10,.03]},moveA:{tentacleBend:[0,.10,.02],tentacleTip:[.02,.16,.03]},moveB:{tentacleBend:[0,-.10,.02],tentacleTip:[.02,-.16,.03]},attack:{tentacleCrest:[.16,0,.04],tentacleBend:[.44,0,.12],tentacleTip:[.72,0,.24]},contacts:['root'],intervals:[{ids:['root'],from:0,to:1}],moveDuration:1200,attackDuration:640,moveEventA:'sway-left',moveEventB:'sway-right'})});
const scorpionLegs=articulatedLegSet({parent:'thorax',pairs:4,xPositions:[.26,.08,-.10,-.28],lateral:.17,reach:.29,upperWidth:.075,lowerWidth:.055,prefix:'Leg'});
const scorpion=templateRig({id:'scorpionBase',family:'scorpion',archetypes:['scorpion','giant scorpion'],height:.46,scale:31,groundY:70,profile:{legs:8,pincers:2,tail:'five-part raised stinger chain'},
  joints:[joint('root',null,V(0,0,0),{role:'root'}),joint('abdomen','root',V(-.16,0,.18),{role:'body'}),joint('thorax','abdomen',V(.40,0,0),{role:'body'}),joint('head','thorax',V(.28,0,.01),{role:'head'}),...scorpionLegs.joints,joint('leftPincerShoulder','head',V(.06,.18,.01),{role:'limb',mirror:'rightPincerShoulder'}),joint('leftPincerElbow','leftPincerShoulder',V(.22,.18,-.03),{role:'limb',mirror:'rightPincerElbow'}),joint('leftPincerClaw','leftPincerElbow',V(.22,-.04,-.04),{role:'pincer',mirror:'rightPincerClaw'}),joint('rightPincerShoulder','head',V(.06,-.18,.01),{role:'limb',mirror:'leftPincerShoulder'}),joint('rightPincerElbow','rightPincerShoulder',V(.22,-.18,-.03),{role:'limb',mirror:'leftPincerElbow'}),joint('rightPincerClaw','rightPincerElbow',V(.22,.04,-.04),{role:'pincer',mirror:'leftPincerClaw'}),joint('tailBase','abdomen',V(-.30,0,.08),{role:'tail'}),joint('tailMid1','tailBase',V(-.24,0,.22),{role:'tail'}),joint('tailMid2','tailMid1',V(.02,0,.30),{role:'tail'}),joint('tailCurl','tailMid2',V(.24,0,.18),{role:'tail'}),joint('stingerTip','tailCurl',V(.28,0,-.08),{role:'stinger',ik:'stingerStrikeChain'})],
  plates:[plate('castShadow','root','ellipse',[1.38,1.10],'shadow',-99),plate('abdomenPlate','abdomen','ellipse',[.58,.54],'body',3),spanPlate('thoraxPlate','abdomen','thorax',.46,'body',3.3),plate('headPlate','head','ellipse',[.35,.42],'accent',3.5),...scorpionLegs.plates,spanPlate('leftPincerUpperPlate','leftPincerShoulder','leftPincerElbow',.11,'body',3.2),spanPlate('leftPincerLowerPlate','leftPincerElbow','leftPincerClaw',.10,'accent',3.3),plate('leftPincerClawPlate','leftPincerClaw','ellipse',[.25,.18],'accent',3.6),spanPlate('rightPincerUpperPlate','rightPincerShoulder','rightPincerElbow',.11,'body',3.2),spanPlate('rightPincerLowerPlate','rightPincerElbow','rightPincerClaw',.10,'accent',3.3),plate('rightPincerClawPlate','rightPincerClaw','ellipse',[.25,.18],'accent',3.6),spanPlate('tailBasePlate','abdomen','tailBase',.22,'body',3.4),spanPlate('tailMid1Plate','tailBase','tailMid1',.19,'body',3.7),spanPlate('tailMid2Plate','tailMid1','tailMid2',.16,'accent',4),spanPlate('tailCurlPlate','tailMid2','tailCurl',.13,'accent',4.3),taperedSpanPlate('stingerPlate','tailCurl','stingerTip',.14,'accent',4.6)],
  anchors:[{id:'stingerTipAnchor',bone:'stingerTip',offset:V(.04,0,0),inheritScale:false},{id:'leftPincerGripAnchor',bone:'leftPincerClaw',offset:V(.04,0,0),counterpart:'rightPincerGripAnchor',inheritScale:false},{id:'rightPincerGripAnchor',bone:'rightPincerClaw',offset:V(.04,0,0),counterpart:'leftPincerGripAnchor',inheritScale:false}],
  clips:clipPack({idle:{tailCurl:[-.03,.03,.03],stingerTip:[-.05,.04,.03]},moveA:{...scorpionLegs.moveA,leftPincerClaw:[.04,-.03,.01]},moveB:{...scorpionLegs.moveB,rightPincerClaw:[.04,.03,.01]},attack:{tailMid2:[.18,0,.05],tailCurl:[.42,0,-.02],stingerTip:[.62,0,-.12],leftPincerClaw:[.18,-.08,.02],rightPincerClaw:[.18,.08,.02]},contacts:scorpionLegs.contacts,intervals:scorpionLegs.intervals,moveDuration:720,attackDuration:610,moveEventA:'octopod-a',moveEventB:'octopod-b'})});
const bat=templateRig({id:'batBase',family:'batFlying',archetypes:['bat','giant bat'],height:.78,scale:24,groundY:78,profile:{silhouette:'compact body with broad pointed and scalloped membrane wings',stance:'airborne'},
  joints:[joint('root',null,V(0,0,0),{role:'root'}),joint('body','root',V(-.10,0,.64),{role:'body'}),joint('chest','body',V(.25,0,.05),{role:'body'}),joint('neck','chest',V(.17,0,.05),{role:'neck'}),joint('head','neck',V(.17,0,.04),{role:'head'}),joint('leftEarBase','head',V(-.02,.09,.08),{role:'ear',mirror:'rightEarBase'}),joint('leftEarTip','leftEarBase',V(-.02,.03,.14),{role:'ear',mirror:'rightEarTip'}),joint('rightEarBase','head',V(-.02,-.09,.08),{role:'ear',mirror:'leftEarBase'}),joint('rightEarTip','rightEarBase',V(-.02,-.03,.14),{role:'ear',mirror:'leftEarTip'}),joint('tailBase','body',V(-.24,0,-.02),{role:'tail'}),joint('tailTip','tailBase',V(-.22,0,-.06),{role:'tail'}),joint('leftWingRoot','chest',V(-.05,.16,.03),{role:'wing',mirror:'rightWingRoot'}),joint('leftWingElbow','leftWingRoot',V(-.04,.48,.02),{role:'wing',mirror:'rightWingElbow'}),joint('leftWingWrist','leftWingElbow',V(-.18,.48,-.04),{role:'wing',mirror:'rightWingWrist'}),joint('leftWingTip','leftWingWrist',V(-.20,.42,-.06),{role:'wing',mirror:'rightWingTip'}),joint('leftWingFinger','leftWingWrist',V(-.32,.24,-.06),{role:'wing',mirror:'rightWingFinger'}),joint('leftWingTrailingRoot','body',V(-.24,.15,-.02),{role:'wing',mirror:'rightWingTrailingRoot'}),joint('rightWingRoot','chest',V(-.05,-.16,.03),{role:'wing',mirror:'leftWingRoot'}),joint('rightWingElbow','rightWingRoot',V(-.04,-.48,.02),{role:'wing',mirror:'leftWingElbow'}),joint('rightWingWrist','rightWingElbow',V(-.18,-.48,-.04),{role:'wing',mirror:'leftWingWrist'}),joint('rightWingTip','rightWingWrist',V(-.20,-.42,-.06),{role:'wing',mirror:'leftWingTip'}),joint('rightWingFinger','rightWingWrist',V(-.32,-.24,-.06),{role:'wing',mirror:'leftWingFinger'}),joint('rightWingTrailingRoot','body',V(-.24,-.15,-.02),{role:'wing',mirror:'leftWingTrailingRoot'})],
  plates:[plate('castShadow','root','ellipse',[1.25,.64],'shadow',-99),spanPlate('bodyPlate','body','chest',.40,'body',3),spanPlate('neckPlate','chest','neck',.19,'body',4),spanPlate('headConnectorPlate','neck','head',.23,'body',4.5),plate('headPlate','head','ellipse',[.30,.34],'body',4.8),taperedSpanPlate('leftEarPlate','leftEarBase','leftEarTip',.11,'accent',5),taperedSpanPlate('rightEarPlate','rightEarBase','rightEarTip',.11,'accent',5),spanPlate('tailPlate','tailBase','tailTip',.11,'accent',2.5),polygonPlate('leftWingMembrane','leftWingRoot',['leftWingRoot','leftWingElbow','leftWingWrist','leftWingTip','leftWingFinger','leftWingTrailingRoot'],'accent',3.6),polygonPlate('rightWingMembrane','rightWingRoot',['rightWingRoot','rightWingTrailingRoot','rightWingFinger','rightWingTip','rightWingWrist','rightWingElbow'],'accent',3.6),...['left','right'].flatMap(s=>[spanPlate(`${s}WingUpperPlate`,`${s}WingRoot`,`${s}WingElbow`,.13,'body',4.1),spanPlate(`${s}WingForePlate`,`${s}WingElbow`,`${s}WingWrist`,.11,'body',4.1),spanPlate(`${s}WingTipPlate`,`${s}WingWrist`,`${s}WingTip`,.08,'accent',4.2),spanPlate(`${s}WingFingerPlate`,`${s}WingWrist`,`${s}WingFinger`,.065,'accent',4)])],
  anchors:[{id:'leftWingTipAnchor',bone:'leftWingTip',offset:V(0,.04,0),counterpart:'rightWingTipAnchor',inheritScale:false},{id:'rightWingTipAnchor',bone:'rightWingTip',offset:V(0,-.04,0),counterpart:'leftWingTipAnchor',inheritScale:false},{id:'headAccessoryAnchor',bone:'head',offset:V(0,0,.15),inheritScale:false}],
  clips:clipPack({idle:{body:[0,0,.03],leftWingTip:[0,.05,.03],rightWingTip:[0,-.05,.03]},moveA:{leftWingElbow:[0,-.13,.14],leftWingWrist:[0,-.20,.20],leftWingTip:[0,-.24,.24],rightWingElbow:[0,.08,-.08],rightWingWrist:[0,.12,-.12],rightWingTip:[0,.16,-.14]},moveB:{leftWingElbow:[0,.08,-.08],leftWingWrist:[0,.12,-.12],leftWingTip:[0,.16,-.14],rightWingElbow:[0,-.13,.14],rightWingWrist:[0,-.20,.20],rightWingTip:[0,-.24,.24]},attack:{head:[.28,0,.03],neck:[.18,0,.02],leftWingTip:[.10,.18,.08],rightWingTip:[.10,-.18,.08]},contacts:[],intervals:[],moveDuration:700,moveEventA:'left-wing-down',moveEventB:'right-wing-down'})});
const crabLegs=articulatedLegSet({parent:'body',pairs:4,xPositions:[.24,.08,-.10,-.26],lateral:.20,reach:.28,upperWidth:.085,lowerWidth:.065,prefix:'Leg'});
const crab=templateRig({id:'crabBase',family:'crustaceanCrab',archetypes:['crab','giant crab'],height:.34,scale:31,groundY:69,profile:{silhouette:'wide oval carapace, four walking-leg pairs, oversized symmetric claws'},
  joints:[joint('root',null,V(0,0,0),{role:'root'}),joint('body','root',V(-.05,0,.18),{role:'body'}),joint('head','body',V(.28,0,.01),{role:'head'}),...crabLegs.joints,joint('leftClawShoulder','head',V(.08,.23,0),{role:'limb',mirror:'rightClawShoulder'}),joint('leftClawElbow','leftClawShoulder',V(.24,.20,-.03),{role:'limb',mirror:'rightClawElbow'}),joint('leftClaw','leftClawElbow',V(.22,-.03,-.05),{role:'claw',mirror:'rightClaw'}),joint('rightClawShoulder','head',V(.08,-.23,0),{role:'limb',mirror:'leftClawShoulder'}),joint('rightClawElbow','rightClawShoulder',V(.24,-.20,-.03),{role:'limb',mirror:'leftClawElbow'}),joint('rightClaw','rightClawElbow',V(.22,.03,-.05),{role:'claw',mirror:'leftClaw'})],
  plates:[plate('castShadow','root','ellipse',[1.28,1.22],'shadow',-99),plate('carapacePlate','body','ellipse',[.66,1.02],'body',3),plate('headPlate','head','ellipse',[.28,.46],'accent',3.3),...crabLegs.plates,...['left','right'].flatMap(s=>[spanPlate(`${s}ClawUpperPlate`,`${s}ClawShoulder`,`${s}ClawElbow`,.12,'body',3.2),spanPlate(`${s}ClawForePlate`,`${s}ClawElbow`,`${s}Claw`,.11,'accent',3.3),plate(`${s}ClawPlate`,`${s}Claw`,'ellipse',[.29,.22],'accent',3.6)])],
  anchors:[{id:'leftClawGripAnchor',bone:'leftClaw',offset:V(.05,0,0),counterpart:'rightClawGripAnchor',inheritScale:false},{id:'rightClawGripAnchor',bone:'rightClaw',offset:V(.05,0,0),counterpart:'leftClawGripAnchor',inheritScale:false},{id:'shellTopAnchor',bone:'body',offset:V(0,0,.14),inheritScale:false}],
  clips:clipPack({idle:{leftClaw:[.02,-.03,.01],rightClaw:[.02,.03,.01]},moveA:{...crabLegs.moveA,leftClaw:[.05,-.04,.02]},moveB:{...crabLegs.moveB,rightClaw:[.05,.04,.02]},attack:{leftClaw:[.36,-.10,.05],rightClaw:[.36,.10,.05],leftClawElbow:[.16,-.05,.02],rightClawElbow:[.16,.05,.02]},contacts:crabLegs.contacts,intervals:crabLegs.intervals,moveDuration:760,moveEventA:'sidestep-a',moveEventB:'sidestep-b'})});
const lobsterLegs=articulatedLegSet({parent:'thorax',pairs:4,xPositions:[.24,.08,-.08,-.24],lateral:.17,reach:.24,upperWidth:.065,lowerWidth:.05,prefix:'Leg'});
const lobster=templateRig({id:'lobsterBase',family:'crustaceanLobster',archetypes:['lobster','giant lobster','crayfish'],height:.30,scale:30,groundY:69,profile:{silhouette:'long segmented body, broad claws, antennae, tail fan'},
  joints:[joint('root',null,V(0,0,0),{role:'root'}),joint('abdomen','root',V(-.24,0,.18),{role:'body'}),joint('thorax','abdomen',V(.38,0,0),{role:'body'}),joint('head','thorax',V(.34,0,.01),{role:'head'}),joint('tailBase','abdomen',V(-.34,0,0),{role:'tail'}),joint('tailMid','tailBase',V(-.28,0,-.01),{role:'tail'}),joint('leftTailFan','tailMid',V(-.18,.14,-.02),{role:'tail',mirror:'rightTailFan'}),joint('rightTailFan','tailMid',V(-.18,-.14,-.02),{role:'tail',mirror:'leftTailFan'}),...lobsterLegs.joints,joint('leftClawShoulder','head',V(.05,.18,0),{role:'limb',mirror:'rightClawShoulder'}),joint('leftClawElbow','leftClawShoulder',V(.25,.18,-.03),{role:'limb',mirror:'rightClawElbow'}),joint('leftClaw','leftClawElbow',V(.24,-.02,-.04),{role:'claw',mirror:'rightClaw'}),joint('rightClawShoulder','head',V(.05,-.18,0),{role:'limb',mirror:'leftClawShoulder'}),joint('rightClawElbow','rightClawShoulder',V(.25,-.18,-.03),{role:'limb',mirror:'leftClawElbow'}),joint('rightClaw','rightClawElbow',V(.24,.02,-.04),{role:'claw',mirror:'leftClaw'}),joint('leftAntennaBase','head',V(.12,.08,.02),{role:'antenna',mirror:'rightAntennaBase'}),joint('leftAntennaTip','leftAntennaBase',V(.48,.16,.01),{role:'antenna',mirror:'rightAntennaTip'}),joint('rightAntennaBase','head',V(.12,-.08,.02),{role:'antenna',mirror:'leftAntennaBase'}),joint('rightAntennaTip','rightAntennaBase',V(.48,-.16,.01),{role:'antenna',mirror:'leftAntennaTip'})],
  plates:[plate('castShadow','root','ellipse',[1.70,.90],'shadow',-99),plate('abdomenPlate','abdomen','ellipse',[.58,.48],'body',3),spanPlate('thoraxPlate','abdomen','thorax',.44,'body',3.2),plate('headPlate','head','ellipse',[.34,.42],'accent',3.4),spanPlate('tailBasePlate','abdomen','tailBase',.30,'body',2.8),spanPlate('tailMidPlate','tailBase','tailMid',.25,'accent',2.7),spanPlate('leftTailFanPlate','tailMid','leftTailFan',.18,'accent',2.6),spanPlate('rightTailFanPlate','tailMid','rightTailFan',.18,'accent',2.6),...lobsterLegs.plates,...['left','right'].flatMap(s=>[spanPlate(`${s}ClawUpperPlate`,`${s}ClawShoulder`,`${s}ClawElbow`,.10,'body',3.2),spanPlate(`${s}ClawForePlate`,`${s}ClawElbow`,`${s}Claw`,.09,'accent',3.3),plate(`${s}ClawPlate`,`${s}Claw`,'ellipse',[.28,.20],'accent',3.5),spanPlate(`${s}AntennaPlate`,`${s}AntennaBase`,`${s}AntennaTip`,.035,'accent',3.1)])],
  anchors:[{id:'leftClawGripAnchor',bone:'leftClaw',offset:V(.05,0,0),counterpart:'rightClawGripAnchor',inheritScale:false},{id:'rightClawGripAnchor',bone:'rightClaw',offset:V(.05,0,0),counterpart:'leftClawGripAnchor',inheritScale:false},{id:'tailFanAnchor',bone:'tailMid',offset:V(-.08,0,0),inheritScale:false}],
  clips:clipPack({idle:{leftAntennaTip:[0,.05,.01],rightAntennaTip:[0,-.05,.01],tailMid:[0,.02,.01]},moveA:{...lobsterLegs.moveA,leftAntennaTip:[.03,-.04,.01]},moveB:{...lobsterLegs.moveB,rightAntennaTip:[.03,.04,.01]},attack:{leftClaw:[.38,-.08,.04],rightClaw:[.38,.08,.04],leftClawElbow:[.15,-.04,.02],rightClawElbow:[.15,.04,.02]},contacts:lobsterLegs.contacts,intervals:lobsterLegs.intervals,moveDuration:800,moveEventA:'crawl-a',moveEventB:'crawl-b'})});
const centaur=JSON.parse(JSON.stringify(horse));
centaur.id='centaurBase';
centaur.family='centaur';
centaur.archetypes=['centaur','horse-bodied humanoid'];
centaur.heightMeters=2.34;
centaur.tokenScale=22;
centaur.tokenGroundY=78;
centaur.camera=topCamera(78);
centaur.profile={silhouette:'horse body whose forward withers transition directly into an upright humanoid torso',locomotion:'diagonal quadruped gait',upperBody:'biped torso without facial details'};
const removedHorseHead=new Set(['neckBase','neckTip','head','muzzle']);
centaur.joints=centaur.joints.filter(j=>!removedHorseHead.has(j.id));
centaur.plates=centaur.plates.filter(p=>!removedHorseHead.has(p.bone)&&!(p.span||[]).some(id=>removedHorseHead.has(id)));
centaur.anchors=centaur.anchors.filter(a=>!removedHorseHead.has(a.bone));
for(const c of Object.values(centaur.clips))for(const f of c.frames)for(const id of removedHorseHead)delete f.poses[id];
centaur.joints.push(joint('upperPelvis','chest',V(-.08,0,.34),{role:'body'}),joint('upperSpine','upperPelvis',V(.03,0,.34),{role:'body'}),joint('upperShoulders','upperSpine',V(.04,0,.27),{role:'body'}),joint('upperNeck','upperShoulders',V(.04,0,.13),{role:'neck'}),joint('upperHead','upperNeck',V(.04,0,.22),{role:'head'}),joint('leftShoulder','upperShoulders',V(0,.28,0),{role:'limb',mirror:'rightShoulder'}),joint('leftElbow','leftShoulder',V(.06,.10,-.27),{role:'limb',mirror:'rightElbow',bendAxis:V(0,0,1),limits:[0,155]}),joint('leftHand','leftElbow',V(.16,-.03,-.25),{role:'limb',mirror:'rightHand'}),joint('rightShoulder','upperShoulders',V(0,-.28,0),{role:'limb',mirror:'leftShoulder'}),joint('rightElbow','rightShoulder',V(.06,-.10,-.27),{role:'limb',mirror:'leftElbow',bendAxis:V(0,0,-1),limits:[0,155]}),joint('rightHand','rightElbow',V(.16,.03,-.25),{role:'limb',mirror:'leftHand'}));
centaur.plates.push(spanPlate('upperTorsoPlate','upperPelvis','upperSpine',.50,'body',4),spanPlate('upperChestPlate','upperSpine','upperShoulders',.62,'body',4.3),plate('upperShoulderPlate','upperShoulders','ellipse',[.68,.30],'accent',4.6),spanPlate('upperNeckPlate','upperShoulders','upperNeck',.20,'body',5),spanPlate('upperHeadConnectorPlate','upperNeck','upperHead',.25,'body',5.2),plate('upperHeadPlate','upperHead','ellipse',[.36,.42],'body',5.5),...['left','right'].flatMap(s=>[spanPlate(`${s}BicepPlate`,`${s}Shoulder`,`${s}Elbow`,.14,'body',4.5),spanPlate(`${s}ForearmPlate`,`${s}Elbow`,`${s}Hand`,.12,'body',4.6),plate(`${s}HandPlate`,`${s}Hand`,'ellipse',[.16,.13],'accent',4.8)]));
centaur.anchors.push({id:'leftGripAnchor',bone:'leftHand',offset:V(.07,0,0),counterpart:'rightGripAnchor',inheritScale:false},{id:'rightGripAnchor',bone:'rightHand',offset:V(.07,0,0),counterpart:'leftGripAnchor',inheritScale:false},{id:'upperHeadgearAnchor',bone:'upperHead',offset:V(0,0,.20),inheritScale:false},{id:'centaurBackAnchor',bone:'upperSpine',offset:V(-.08,0,.18),inheritScale:false});
centaur.clips.idleA.frames[1].poses.upperHead=V(0,0,.02);
centaur.clips.walkA.frames[0].poses.leftHand=V(-.08,0,0);
centaur.clips.walkA.frames[0].poses.rightHand=V(.08,0,0);
centaur.clips.walkA.frames[1].poses.leftHand=V(.08,0,0);
centaur.clips.walkA.frames[1].poses.rightHand=V(-.08,0,0);
centaur.clips.walkA.frames[2].poses.leftHand=V(-.08,0,0);
centaur.clips.walkA.frames[2].poses.rightHand=V(.08,0,0);
centaur.clips.attack.frames[1].poses.leftElbow=V(.08,-.10,.04);
centaur.clips.attack.frames[1].poses.leftHand=V(.46,-.28,.10);
function addHumanoidWingPair(rig,{span=1,fold=.55}={}){rig.joints.push(joint('leftWingRoot','upperBack',V(-.04,.16,.06),{role:'wing',mirror:'rightWingRoot'}),joint('leftWingElbow','leftWingRoot',V(-.10,.36*fold,.04),{role:'wing',mirror:'rightWingElbow',bendAxis:V(1,0,0),limits:[-30,135]}),joint('leftWingTip','leftWingElbow',V(-.18,.42*span,-.04),{role:'wing',mirror:'rightWingTip'}),joint('leftWingTrailingRoot','upperBack',V(-.48,.13,-.07),{role:'wing',mirror:'rightWingTrailingRoot'}),joint('leftWingTrailingMid','leftWingElbow',V(-.34,-.10,-.05),{role:'wing',mirror:'rightWingTrailingMid'}),joint('leftWingTrailingTip','leftWingTip',V(-.32,-.16,-.05),{role:'wing',mirror:'rightWingTrailingTip'}),joint('rightWingRoot','upperBack',V(-.04,-.16,.06),{role:'wing',mirror:'leftWingRoot'}),joint('rightWingElbow','rightWingRoot',V(-.10,-.36*fold,.04),{role:'wing',mirror:'leftWingElbow',bendAxis:V(-1,0,0),limits:[-30,135]}),joint('rightWingTip','rightWingElbow',V(-.18,-.42*span,-.04),{role:'wing',mirror:'leftWingTip'}),joint('rightWingTrailingRoot','upperBack',V(-.48,-.13,-.07),{role:'wing',mirror:'leftWingTrailingRoot'}),joint('rightWingTrailingMid','rightWingElbow',V(-.34,.10,-.05),{role:'wing',mirror:'leftWingTrailingMid'}),joint('rightWingTrailingTip','rightWingTip',V(-.32,.16,-.05),{role:'wing',mirror:'leftWingTrailingTip'}));rig.plates.push(polygonPlate('leftWingMembrane','leftWingRoot',['leftWingRoot','leftWingElbow','leftWingTip','leftWingTrailingTip','leftWingTrailingMid','leftWingTrailingRoot'],'accent',3.8),polygonPlate('rightWingMembrane','rightWingRoot',['rightWingRoot','rightWingTrailingRoot','rightWingTrailingMid','rightWingTrailingTip','rightWingTip','rightWingElbow'],'accent',3.8),spanPlate('leftWingUpperPlate','leftWingRoot','leftWingElbow',.16,'body',4.2),spanPlate('leftWingForePlate','leftWingElbow','leftWingTip',.12,'accent',4.1),spanPlate('rightWingUpperPlate','rightWingRoot','rightWingElbow',.16,'body',4.2),spanPlate('rightWingForePlate','rightWingElbow','rightWingTip',.12,'accent',4.1));rig.anchors.push({id:'leftWingTipAnchor',bone:'leftWingTip',offset:V(0,.05,0),counterpart:'rightWingTipAnchor',inheritScale:false},{id:'rightWingTipAnchor',bone:'rightWingTip',offset:V(0,-.05,0),counterpart:'leftWingTipAnchor',inheritScale:false});rig.clips.idleA.frames[1].poses.leftWingTip=V(0,.04,.03);rig.clips.idleA.frames[1].poses.rightWingTip=V(0,-.04,.03);rig.clips.walkA.frames[0].poses.leftWingTip=V(0,-.10,.12);rig.clips.walkA.frames[0].poses.rightWingTip=V(0,.06,-.06);rig.clips.walkA.frames[1].poses.leftWingTip=V(0,.06,-.06);rig.clips.walkA.frames[1].poses.rightWingTip=V(0,-.10,.12);rig.clips.walkA.frames[2].poses.leftWingTip=V(0,-.10,.12);rig.clips.walkA.frames[2].poses.rightWingTip=V(0,.06,-.06);rig.clips.attack.frames[1].poses.leftWingTip=V(.16,.28,.10);rig.clips.attack.frames[1].poses.rightWingTip=V(.16,-.28,.10)}
function wingedBiped({id,family,archetypes,height,arms}){const rig=bipedVariant({id,archetypes,height,sx:1,sy:1.02,sz:1.02,headScale:1.0,scale:27,profile:{silhouette:arms?'humanoid with independent arms and broad back wings':'humanoid torso with broad wings replacing arms',wings:'paired articulated membrane wings'}});rig.family=family;rig.camera=topCamera(78);rig.joints.push(joint('upperBack','shoulders',V(-.08,0,.03),{role:'body'}));if(!arms){const remove=new Set(['nearShoulder','nearElbow','nearHand','farShoulder','farElbow','farHand']);rig.joints=rig.joints.filter(j=>!remove.has(j.id));rig.plates=rig.plates.filter(p=>!remove.has(p.bone)&&!(p.span||[]).some(id=>remove.has(id))&&!/Bicep|Forearm|HandPlate/.test(p.id));rig.anchors=rig.anchors.filter(a=>!remove.has(a.bone));for(const c of Object.values(rig.clips))for(const f of c.frames)for(const id of remove)delete f.poses[id]}addHumanoidWingPair(rig,{span:arms?1.12:1.32,fold:arms?.74:.92});return rig}
const harpy=wingedBiped({id:'harpyBase',family:'harpy',archetypes:['harpy','wing-armed humanoid'],height:1.62,arms:false});
harpy.profile.feet='talon-like biped contacts';
harpy.plates.find(p=>p.id==='nearFootPlate').id='leftTalonPlate';
harpy.plates.find(p=>p.id==='farFootPlate').id='rightTalonPlate';
const angel=wingedBiped({id:'angelBase',family:'angel',archetypes:['angel','winged humanoid'],height:1.84,arms:true});
angel.profile.attachments='hands remain available for weapons while wings animate independently';
const spiderLegs=articulatedLegSet({parent:'cephalothorax',pairs:4,xPositions:[.28,.09,-.10,-.28],lateral:.17,reach:.36,upperWidth:.075,lowerWidth:.055,prefix:'Leg'});
const spider=templateRig({id:'spiderBase',family:'spider',archetypes:['giant spider','tarantula-like monster'],height:.42,scale:29,groundY:70,profile:{legs:8,segmentsPerLeg:2,fangs:2,silhouette:'large abdomen and radial articulated legs'},
  joints:[joint('root',null,V(0,0,0),{role:'root'}),joint('abdomen','root',V(-.24,0,.18),{role:'body'}),joint('cephalothorax','abdomen',V(.42,0,0),{role:'body'}),joint('head','cephalothorax',V(.26,0,.01),{role:'head'}),...spiderLegs.joints,joint('leftFangBase','head',V(.10,.08,-.01),{role:'fang',mirror:'rightFangBase'}),joint('leftFangTip','leftFangBase',V(.18,-.02,-.08),{role:'fang',mirror:'rightFangTip'}),joint('rightFangBase','head',V(.10,-.08,-.01),{role:'fang',mirror:'leftFangBase'}),joint('rightFangTip','rightFangBase',V(.18,.02,-.08),{role:'fang',mirror:'leftFangTip'})],
  plates:[plate('castShadow','root','ellipse',[1.42,1.30],'shadow',-99),plate('abdomenPlate','abdomen','ellipse',[.66,.58],'body',3),spanPlate('cephalothoraxPlate','abdomen','cephalothorax',.46,'body',3.3),plate('headPlate','head','ellipse',[.31,.37],'accent',3.5),...spiderLegs.plates,taperedSpanPlate('leftFangPlate','leftFangBase','leftFangTip',.105,'accent',4),taperedSpanPlate('rightFangPlate','rightFangBase','rightFangTip',.105,'accent',4)],
  anchors:[{id:'leftFangTipAnchor',bone:'leftFangTip',offset:V(.03,0,0),counterpart:'rightFangTipAnchor',inheritScale:false},{id:'rightFangTipAnchor',bone:'rightFangTip',offset:V(.03,0,0),counterpart:'leftFangTipAnchor',inheritScale:false},{id:'abdomenTopAnchor',bone:'abdomen',offset:V(0,0,.16),inheritScale:false}],
  clips:clipPack({idle:{abdomen:[-.02,0,.02],leftFangTip:[.02,-.01,.01],rightFangTip:[.02,.01,.01]},moveA:spiderLegs.moveA,moveB:spiderLegs.moveB,attack:{head:[.20,0,.02],leftFangTip:[.24,-.04,.02],rightFangTip:[.24,.04,.02]},contacts:spiderLegs.contacts,intervals:spiderLegs.intervals,moveDuration:660,attackDuration:560,moveEventA:'octopod-a',moveEventB:'octopod-b'})});
const rigs={horse,humanoid,tinyBiped,stoutBiped,tailedBiped,rhino,elephant,rabbit,leopard,wolf,greyhound,blob,quadruped,lizard,dragon,walkingBird,flyingBird,bug,ant,radial,serpentine,mimic,tentacle,scorpion,bat,crab,lobster,centaur,harpy,angel,spider};
function setRotationalAttack(rig,rotations,{impact=.62,events}={}){const old=rig.clips.attack;rig.clips.attack={...old,boneLengthPolicy:'preserve',motionSemantics:'joint-local rotation; no child-bone translation',frames:[{t:0,poses:{},rotations:{}},{t:impact,poses:{},rotations},{t:1,poses:{},rotations:{}}],events:events||old.events||[{t:impact,name:'impact'},{t:.84,name:'release'}]}}
setRotationalAttack(horse,{neckBase:V(0,28,0),neckTip:V(0,18,0),head:V(0,-10,0)});
for(const rig of[humanoid,tinyBiped,stoutBiped,tailedBiped,angel])setRotationalAttack(rig,{nearShoulder:V(0,-25,-70),nearElbow:V(0,10,70),...(rig===tailedBiped?{tailBase:V(0,0,12)}:{})});
for(const rig of[quadruped,rhino,elephant,rabbit,leopard,wolf,greyhound])setRotationalAttack(rig,{neck:V(0,28,0),head:V(0,-12,0),...(rig===elephant?{trunkBase:V(0,22,0),trunkMid:V(0,-38,0)}:{})});
setRotationalAttack(lizard,{neck:V(0,24,0),head:V(0,-10,0),tailBase:V(0,0,10)});
setRotationalAttack(dragon,{neck:V(0,24,0),head:V(0,-10,0),nearWingRoot:V(0,0,-18),farWingRoot:V(0,0,18),tailBase:V(0,0,10)});
setRotationalAttack(walkingBird,{neck:V(0,34,0),head:V(0,-14,0)});
setRotationalAttack(flyingBird,{body:V(0,8,0),neck:V(0,30,0),head:V(0,-12,0)});
setRotationalAttack(blob,{nearArm:V(0,0,-48),nearHand:V(0,0,24),middleMass:V(0,8,0)});
setRotationalAttack(bug,{body:V(0,10,0),nearFrontFoot:V(0,0,-18),farFrontFoot:V(0,0,18)});
setRotationalAttack(ant,{head:V(0,12,0),nearAntennaBase:V(0,0,-18),farAntennaBase:V(0,0,18)});
setRotationalAttack(radial,{tentacle0Base:V(0,0,-34),tentacle0Mid:V(0,0,22)});
setRotationalAttack(serpentine,{frontSpine:V(0,0,-22),neck:V(0,0,34),head:V(0,0,-12)});
mimic.clips.attack={...mimic.clips.attack,boneLengthPolicy:'preserve',motionSemantics:'rear-hinge rotation with fixed lid length',frames:[{t:0,poses:{},rotations:{rearHinge:V(0,0,0)}},{t:.45,poses:{},rotations:{rearHinge:V(0,-76,0)}},{t:.62,poses:{},rotations:{rearHinge:V(0,-12,0)}},{t:1,poses:{},rotations:{rearHinge:V(0,0,0)}}]};
setRotationalAttack(tentacle,{tentacleBase:V(0,46,0),tentacleLower:V(0,28,0),tentacleCrest:V(0,-24,0),tentacleBend:V(0,-18,0)});
setRotationalAttack(scorpion,{tailBase:V(0,55,0),tailMid1:V(0,35,0),tailMid2:V(0,-40,0),tailCurl:V(0,-50,0),leftPincerShoulder:V(0,0,-32),leftPincerElbow:V(0,0,18),rightPincerShoulder:V(0,0,32),rightPincerElbow:V(0,0,-18)});
setRotationalAttack(bat,{neck:V(0,28,0),head:V(0,-10,0),leftWingRoot:V(0,0,-14),rightWingRoot:V(0,0,14)});
for(const rig of[crab,lobster])setRotationalAttack(rig,{leftClawShoulder:V(0,0,-36),leftClawElbow:V(0,0,20),rightClawShoulder:V(0,0,36),rightClawElbow:V(0,0,-20)});
setRotationalAttack(centaur,{leftShoulder:V(0,-25,-70),leftElbow:V(0,10,70),upperSpine:V(0,0,-6)});
setRotationalAttack(harpy,{leftWingRoot:V(0,0,-22),leftWingElbow:V(0,0,16),rightWingRoot:V(0,0,22),rightWingElbow:V(0,0,-16)});
setRotationalAttack(spider,{leftFangBase:V(0,0,-30),rightFangBase:V(0,0,30),cephalothorax:V(0,8,0)});
const rotationalGait=(rig,rotationsA,rotationsB,{posesA={},posesB={},policy='preserve',semantics='parent-joint rotation moves upper and lower limb plates together'}={})=>{const old=rig.clips.walkA;rig.clips.walkA={...old,boneLengthPolicy:policy,motionSemantics:semantics,frames:[{t:0,poses:posesA,rotations:rotationsA},{t:.5,poses:posesB,rotations:rotationsB},{t:1,poses:posesA,rotations:rotationsA}]}};
const rabbitGaitA={nearFrontHip:V(0,-28,0),nearFrontKnee:V(0,38,0),farRearHip:V(0,-24,0),farRearKnee:V(0,42,0)},rabbitGaitB={farFrontHip:V(0,-28,0),farFrontKnee:V(0,38,0),nearRearHip:V(0,-24,0),nearRearKnee:V(0,42,0)};
rotationalGait(rabbit,rabbitGaitA,rabbitGaitB,{semantics:'compact under-body limbs rotate as complete chains; no stretched endpoint-only plates'});
const lizardGaitA={nearFrontShoulder:V(13,0,-20),nearFrontElbow:V(5,0,14),farRearHip:V(-13,0,20),farRearKnee:V(-5,0,-14),tailBase:V(0,0,10),tailMid:V(0,0,-18)},lizardGaitB={farFrontShoulder:V(-13,0,20),farFrontElbow:V(-5,0,-14),nearRearHip:V(13,0,-20),nearRearKnee:V(5,0,14),tailBase:V(0,0,-10),tailMid:V(0,0,18)};
rotationalGait(lizard,lizardGaitA,lizardGaitB,{semantics:'splayed shoulder and hip rotations carry both upper and lower plates; tail wave also preserves segment lengths'});
rotationalGait(dragon,lizardGaitA,lizardGaitB,{posesA:JSON.parse(JSON.stringify(dragon.clips.walkA.frames[0].poses)),posesB:JSON.parse(JSON.stringify(dragon.clips.walkA.frames[1].poses)),policy:'preserve-leg-and-tail-chains',semantics:'lizard gait rotates full leg chains while wing controls retain their authored flap'});
dragon.clips.walkA.contactIntervals=JSON.parse(JSON.stringify(lizard.clips.walkA.contactIntervals));
serpentine.clips.walkA={...serpentine.clips.walkA,boneLengthPolicy:'preserve',motionSemantics:'alternating local Z rotations propagate a continuous lateral wave',frames:[{t:0,poses:{},rotations:{tailBase:V(0,0,20),tailMid:V(0,0,-36),rearSpine:V(0,0,42),middleSpine:V(0,0,-42),frontSpine:V(0,0,36),neck:V(0,0,-24),head:V(0,0,12)}},{t:.5,poses:{},rotations:{tailBase:V(0,0,-20),tailMid:V(0,0,36),rearSpine:V(0,0,-42),middleSpine:V(0,0,42),frontSpine:V(0,0,-36),neck:V(0,0,24),head:V(0,0,-12)}},{t:1,poses:{},rotations:{tailBase:V(0,0,20),tailMid:V(0,0,-36),rearSpine:V(0,0,42),middleSpine:V(0,0,-42),frontSpine:V(0,0,36),neck:V(0,0,-24),head:V(0,0,12)}}]};
harpy.clips.attack={...harpy.clips.attack,boneLengthPolicy:'preserve',motionSemantics:'both legs lift and kick forward while paired arm-wings flap; all motion is joint-local rotation',contacts:[],contactIntervals:[],frames:[{t:0,poses:{},rotations:{}},{t:.28,poses:{},rotations:{nearHip:V(0,-26,0),nearKnee:V(0,58,0),farHip:V(0,-26,0),farKnee:V(0,58,0),leftWingRoot:V(34,0,-14),leftWingElbow:V(0,0,20),rightWingRoot:V(-34,0,14),rightWingElbow:V(0,0,-20)}},{t:.62,poses:{},rotations:{nearHip:V(0,-62,0),nearKnee:V(0,24,0),farHip:V(0,-62,0),farKnee:V(0,24,0),leftWingRoot:V(-28,0,-24),leftWingElbow:V(0,0,12),rightWingRoot:V(28,0,24),rightWingElbow:V(0,0,-12)}},{t:1,poses:{},rotations:{}}],events:[{t:.18,name:'takeoff'},{t:.62,name:'double-kick-impact'},{t:.84,name:'release'}]};
function ensureCanonicalClips(rig){const ground=[...new Set(Object.values(rig.clips).flatMap(c=>[...(c.contacts||[]),...(c.contactIntervals||[]).flatMap(i=>i.ids)]))],idle=cloneData(rig.clips.idleA),walk=cloneData(rig.clips.walkA);rig.clips.idle={...idle,id:'idle',aliasOf:'idleA',base:'bind'};rig.clips.walk={...walk,id:'walk',aliasOf:'walkA',base:'idle'};rig.clips.hit={id:'hit',base:'idle',duration:460,easing:'cubic-bezier(.2,.8,.3,1)',loop:false,frames:[{t:0,poses:{},rotations:{}},{t:.35,poses:{root:V(-.06,0,0)},rotations:{}},{t:1,poses:{},rotations:{}}],contacts:ground,events:[{t:.05,name:'hit-start'},{t:.35,name:'recoil'},{t:.82,name:'recover'}]};rig.clips.ko={id:'ko',base:'bind',duration:900,easing:'ease-in',loop:false,frames:[{t:0,poses:{},rotations:{}},{t:1,poses:{root:V(0,.10,.04)},rotations:{root:V(0,72,0)}}],contactIntervals:ground.length?[{ids:ground,from:0,to:.05}]:[],events:[{t:.5,name:'fall'},{t:1,name:'down'}]}}
Object.values(rigs).forEach(ensureCanonicalClips);
function inferredAnchorModule(id){const s=id.toLowerCase();return/grip|weapon/.test(s)?'weapon':/horn|antler/.test(s)?'horn-or-antler':/headgear|hat/.test(s)?'hat':/helmet/.test(s)?'helmet':/ear/.test(s)?'ear':/saddle|rider/.test(s)?'saddle':/collar/.test(s)?'collar':/wing/.test(s)?'wing':/tail/.test(s)?'tail':/back/.test(s)?'backItem':'generic'}
Object.values(rigs).forEach(r=>r.anchors.forEach(a=>a.moduleType??=inferredAnchorModule(a.id)));
for(const rig of[humanoid,tinyBiped,stoutBiped,tailedBiped,angel]){Object.assign(rig.plates.find(p=>p.id==='shoulderPlate'),{size:[.34,.14],role:'body',bodyRegion:'core',zBias:4.35});rig.plates.push(plate('nearShoulderCapPlate','nearShoulder','ellipse',[.24,.20],'accent',4.5),plate('farShoulderCapPlate','farShoulder','ellipse',[.24,.20],'accent',4.5))}
Object.assign(centaur.plates.find(p=>p.id==='upperShoulderPlate'),{size:[.32,.13],role:'body',bodyRegion:'core',zBias:4.4});
centaur.plates.push(plate('leftShoulderCapPlate','leftShoulder','ellipse',[.22,.18],'accent',4.6),plate('rightShoulderCapPlate','rightShoulder','ellipse',[.22,.18],'accent',4.6));
for(const id of['nearTuskPlate','farTuskPlate'])Object.assign(elephant.plates.find(p=>p.id===id),{role:'tusk',occlusionMode:'surface-relative',occlusionReference:'head'});
for(const p of rabbit.plates)if(/(Front|Rear)(Upper|Lower|Paw)Plate$/.test(p.id))Object.assign(p,{occlusionMode:'under-core',occlusionReference:/Front/.test(p.id)?'chest':'pelvis'});
for(const p of spider.plates)if(/^(left|right)Leg\dUpperPlate$/.test(p.id))Object.assign(p,{occlusionMode:'under-core',occlusionReference:'cephalothorax'});
