#!/usr/bin/env node
// Derive a thin declarative model for every creature by diffing its raw family
// base (rigs/families/<name>.json) against the golden normalized rig
// (fixtures/rigs/<name>.json). The resolver auto-applies canonical-clip
// derivation and anchor-module inference, so a model only needs to carry what
// those can't reproduce: the normalized source clips (attack/gait) and the
// post-normalization plate/anchor field edits (occlusion, tusk role, ...).
//
//   node scripts/gen-models.mjs
//
// rabbit and quadruped are authored by hand (they demonstrate the shared-family
// variant pattern) and are left untouched.

import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { inferredAnchorModule } from '../rigs/family-kit.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const readJSON = (p) => JSON.parse(readFileSync(p, 'utf8'));
const eq = (a, b) => JSON.stringify(a) === JSON.stringify(b);
const HAND_AUTHORED = new Set(['rabbit', 'quadruped']);

// Field-level diff of two plain objects: keys where `after` adds to or changes
// `before`. (Normalization only adds/edits fields, never removes them.)
function fieldDiff(before, after) {
  const set = {};
  for (const k of Object.keys(after)) if (!eq(before[k], after[k])) set[k] = after[k];
  return set;
}

const families = readdirSync(join(ROOT, 'rigs/families')).filter((f) => f.endsWith('.json'));
let count = 0;
for (const file of families) {
  const name = file.replace(/\.json$/, '');
  if (HAND_AUTHORED.has(name)) continue;

  const base = readJSON(join(ROOT, 'rigs/families', file));
  const golden = readJSON(join(ROOT, 'fixtures/rigs', file));

  // 1. Source-clip overrides: base clips (idleA/walkA/attack/...) whose golden
  //    form differs after normalization. idle/walk/hit/ko are canonical-derived
  //    and regenerated by the resolver, so they are never carried here.
  const clips = {};
  for (const k of Object.keys(base.clips)) {
    if (!eq(base.clips[k], golden.clips[k])) clips[k] = golden.clips[k];
  }

  // 2. Plate field overrides (occlusion mode/reference, tusk role, ...).
  const baseP = new Map(base.plates.map((p) => [p.id, p]));
  const plateOverrides = [];
  for (const g of golden.plates) {
    const set = fieldDiff(baseP.get(g.id) || {}, g);
    if (Object.keys(set).length) plateOverrides.push({ id: g.id, set });
  }

  // 3. Anchor overrides only where auto module-type inference wouldn't match.
  const baseA = new Map(base.anchors.map((a) => [a.id, a]));
  const anchorOverrides = [];
  for (const g of golden.anchors) {
    const b = baseA.get(g.id) || {};
    const set = fieldDiff(b, g);
    const expectedModule = b.moduleType ?? inferredAnchorModule(g.id);
    if (set.moduleType !== undefined && set.moduleType === expectedModule) delete set.moduleType;
    if (Object.keys(set).length) anchorOverrides.push({ id: g.id, set });
  }

  const model = { $schema: 'paper-rig/model-1', family: name, base: true };
  if (Object.keys(clips).length) model.clips = clips;
  if (plateOverrides.length) model.plateOverrides = plateOverrides;
  if (anchorOverrides.length) model.anchorOverrides = anchorOverrides;

  writeFileSync(join(ROOT, 'rigs/models', `${name}.json`), JSON.stringify(model, null, 2) + '\n');
  count++;
}
console.log(`wrote ${count} declarative models to rigs/models/`);
